// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/fs.proto

package fs

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorExecute_Type int32

const (
	ErrorExecute_ERROR ErrorExecute_Type = 0
	ErrorExecute_USAGE ErrorExecute_Type = 1
)

var ErrorExecute_Type_name = map[int32]string{
	0: "ERROR",
	1: "USAGE",
}

var ErrorExecute_Type_value = map[string]int32{
	"ERROR": 0,
	"USAGE": 1,
}

func (x ErrorExecute_Type) String() string {
	return proto.EnumName(ErrorExecute_Type_name, int32(x))
}

func (ErrorExecute_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{14, 0}
}

type OriginateRequest_Strategy int32

const (
	OriginateRequest_FAILOVER OriginateRequest_Strategy = 0
	OriginateRequest_MULTIPLE OriginateRequest_Strategy = 1
)

var OriginateRequest_Strategy_name = map[int32]string{
	0: "FAILOVER",
	1: "MULTIPLE",
}

var OriginateRequest_Strategy_value = map[string]int32{
	"FAILOVER": 0,
	"MULTIPLE": 1,
}

func (x OriginateRequest_Strategy) String() string {
	return proto.EnumName(OriginateRequest_Strategy_name, int32(x))
}

func (OriginateRequest_Strategy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{19, 0}
}

type SetProfileVarRequest struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Variables            map[string]string `protobuf:"bytes,2,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SetProfileVarRequest) Reset()         { *m = SetProfileVarRequest{} }
func (m *SetProfileVarRequest) String() string { return proto.CompactTextString(m) }
func (*SetProfileVarRequest) ProtoMessage()    {}
func (*SetProfileVarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{0}
}

func (m *SetProfileVarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetProfileVarRequest.Unmarshal(m, b)
}
func (m *SetProfileVarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetProfileVarRequest.Marshal(b, m, deterministic)
}
func (m *SetProfileVarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetProfileVarRequest.Merge(m, src)
}
func (m *SetProfileVarRequest) XXX_Size() int {
	return xxx_messageInfo_SetProfileVarRequest.Size(m)
}
func (m *SetProfileVarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetProfileVarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetProfileVarRequest proto.InternalMessageInfo

func (m *SetProfileVarRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SetProfileVarRequest) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

type SetProfileVarResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetProfileVarResponse) Reset()         { *m = SetProfileVarResponse{} }
func (m *SetProfileVarResponse) String() string { return proto.CompactTextString(m) }
func (*SetProfileVarResponse) ProtoMessage()    {}
func (*SetProfileVarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{1}
}

func (m *SetProfileVarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetProfileVarResponse.Unmarshal(m, b)
}
func (m *SetProfileVarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetProfileVarResponse.Marshal(b, m, deterministic)
}
func (m *SetProfileVarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetProfileVarResponse.Merge(m, src)
}
func (m *SetProfileVarResponse) XXX_Size() int {
	return xxx_messageInfo_SetProfileVarResponse.Size(m)
}
func (m *SetProfileVarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetProfileVarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetProfileVarResponse proto.InternalMessageInfo

type StopPlaybackRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopPlaybackRequest) Reset()         { *m = StopPlaybackRequest{} }
func (m *StopPlaybackRequest) String() string { return proto.CompactTextString(m) }
func (*StopPlaybackRequest) ProtoMessage()    {}
func (*StopPlaybackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{2}
}

func (m *StopPlaybackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopPlaybackRequest.Unmarshal(m, b)
}
func (m *StopPlaybackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopPlaybackRequest.Marshal(b, m, deterministic)
}
func (m *StopPlaybackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopPlaybackRequest.Merge(m, src)
}
func (m *StopPlaybackRequest) XXX_Size() int {
	return xxx_messageInfo_StopPlaybackRequest.Size(m)
}
func (m *StopPlaybackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopPlaybackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopPlaybackRequest proto.InternalMessageInfo

func (m *StopPlaybackRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type StopPlaybackResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopPlaybackResponse) Reset()         { *m = StopPlaybackResponse{} }
func (m *StopPlaybackResponse) String() string { return proto.CompactTextString(m) }
func (*StopPlaybackResponse) ProtoMessage()    {}
func (*StopPlaybackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{3}
}

func (m *StopPlaybackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopPlaybackResponse.Unmarshal(m, b)
}
func (m *StopPlaybackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopPlaybackResponse.Marshal(b, m, deterministic)
}
func (m *StopPlaybackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopPlaybackResponse.Merge(m, src)
}
func (m *StopPlaybackResponse) XXX_Size() int {
	return xxx_messageInfo_StopPlaybackResponse.Size(m)
}
func (m *StopPlaybackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopPlaybackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopPlaybackResponse proto.InternalMessageInfo

type BridgeCallRequest struct {
	LegAId               string            `protobuf:"bytes,1,opt,name=leg_a_id,json=legAId,proto3" json:"leg_a_id,omitempty"`
	LegBId               string            `protobuf:"bytes,2,opt,name=leg_b_id,json=legBId,proto3" json:"leg_b_id,omitempty"`
	Variables            map[string]string `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BridgeCallRequest) Reset()         { *m = BridgeCallRequest{} }
func (m *BridgeCallRequest) String() string { return proto.CompactTextString(m) }
func (*BridgeCallRequest) ProtoMessage()    {}
func (*BridgeCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{4}
}

func (m *BridgeCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BridgeCallRequest.Unmarshal(m, b)
}
func (m *BridgeCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BridgeCallRequest.Marshal(b, m, deterministic)
}
func (m *BridgeCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BridgeCallRequest.Merge(m, src)
}
func (m *BridgeCallRequest) XXX_Size() int {
	return xxx_messageInfo_BridgeCallRequest.Size(m)
}
func (m *BridgeCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BridgeCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BridgeCallRequest proto.InternalMessageInfo

func (m *BridgeCallRequest) GetLegAId() string {
	if m != nil {
		return m.LegAId
	}
	return ""
}

func (m *BridgeCallRequest) GetLegBId() string {
	if m != nil {
		return m.LegBId
	}
	return ""
}

func (m *BridgeCallRequest) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

type BridgeCallResponse struct {
	Error                *ErrorExecute `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BridgeCallResponse) Reset()         { *m = BridgeCallResponse{} }
func (m *BridgeCallResponse) String() string { return proto.CompactTextString(m) }
func (*BridgeCallResponse) ProtoMessage()    {}
func (*BridgeCallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{5}
}

func (m *BridgeCallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BridgeCallResponse.Unmarshal(m, b)
}
func (m *BridgeCallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BridgeCallResponse.Marshal(b, m, deterministic)
}
func (m *BridgeCallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BridgeCallResponse.Merge(m, src)
}
func (m *BridgeCallResponse) XXX_Size() int {
	return xxx_messageInfo_BridgeCallResponse.Size(m)
}
func (m *BridgeCallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BridgeCallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BridgeCallResponse proto.InternalMessageInfo

func (m *BridgeCallResponse) GetError() *ErrorExecute {
	if m != nil {
		return m.Error
	}
	return nil
}

type HoldRequest struct {
	Id                   []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HoldRequest) Reset()         { *m = HoldRequest{} }
func (m *HoldRequest) String() string { return proto.CompactTextString(m) }
func (*HoldRequest) ProtoMessage()    {}
func (*HoldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{6}
}

func (m *HoldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HoldRequest.Unmarshal(m, b)
}
func (m *HoldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HoldRequest.Marshal(b, m, deterministic)
}
func (m *HoldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HoldRequest.Merge(m, src)
}
func (m *HoldRequest) XXX_Size() int {
	return xxx_messageInfo_HoldRequest.Size(m)
}
func (m *HoldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HoldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HoldRequest proto.InternalMessageInfo

func (m *HoldRequest) GetId() []string {
	if m != nil {
		return m.Id
	}
	return nil
}

type HoldResponse struct {
	Id                   []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HoldResponse) Reset()         { *m = HoldResponse{} }
func (m *HoldResponse) String() string { return proto.CompactTextString(m) }
func (*HoldResponse) ProtoMessage()    {}
func (*HoldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{7}
}

func (m *HoldResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HoldResponse.Unmarshal(m, b)
}
func (m *HoldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HoldResponse.Marshal(b, m, deterministic)
}
func (m *HoldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HoldResponse.Merge(m, src)
}
func (m *HoldResponse) XXX_Size() int {
	return xxx_messageInfo_HoldResponse.Size(m)
}
func (m *HoldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HoldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HoldResponse proto.InternalMessageInfo

func (m *HoldResponse) GetId() []string {
	if m != nil {
		return m.Id
	}
	return nil
}

type UnHoldRequest struct {
	Id                   []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnHoldRequest) Reset()         { *m = UnHoldRequest{} }
func (m *UnHoldRequest) String() string { return proto.CompactTextString(m) }
func (*UnHoldRequest) ProtoMessage()    {}
func (*UnHoldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{8}
}

func (m *UnHoldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnHoldRequest.Unmarshal(m, b)
}
func (m *UnHoldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnHoldRequest.Marshal(b, m, deterministic)
}
func (m *UnHoldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnHoldRequest.Merge(m, src)
}
func (m *UnHoldRequest) XXX_Size() int {
	return xxx_messageInfo_UnHoldRequest.Size(m)
}
func (m *UnHoldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnHoldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnHoldRequest proto.InternalMessageInfo

func (m *UnHoldRequest) GetId() []string {
	if m != nil {
		return m.Id
	}
	return nil
}

type UnHoldResponse struct {
	Id                   []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnHoldResponse) Reset()         { *m = UnHoldResponse{} }
func (m *UnHoldResponse) String() string { return proto.CompactTextString(m) }
func (*UnHoldResponse) ProtoMessage()    {}
func (*UnHoldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{9}
}

func (m *UnHoldResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnHoldResponse.Unmarshal(m, b)
}
func (m *UnHoldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnHoldResponse.Marshal(b, m, deterministic)
}
func (m *UnHoldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnHoldResponse.Merge(m, src)
}
func (m *UnHoldResponse) XXX_Size() int {
	return xxx_messageInfo_UnHoldResponse.Size(m)
}
func (m *UnHoldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnHoldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnHoldResponse proto.InternalMessageInfo

func (m *UnHoldResponse) GetId() []string {
	if m != nil {
		return m.Id
	}
	return nil
}

type HangupManyRequest struct {
	Id                   []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	Cause                string   `protobuf:"bytes,2,opt,name=cause,proto3" json:"cause,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HangupManyRequest) Reset()         { *m = HangupManyRequest{} }
func (m *HangupManyRequest) String() string { return proto.CompactTextString(m) }
func (*HangupManyRequest) ProtoMessage()    {}
func (*HangupManyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{10}
}

func (m *HangupManyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HangupManyRequest.Unmarshal(m, b)
}
func (m *HangupManyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HangupManyRequest.Marshal(b, m, deterministic)
}
func (m *HangupManyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HangupManyRequest.Merge(m, src)
}
func (m *HangupManyRequest) XXX_Size() int {
	return xxx_messageInfo_HangupManyRequest.Size(m)
}
func (m *HangupManyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HangupManyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HangupManyRequest proto.InternalMessageInfo

func (m *HangupManyRequest) GetId() []string {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *HangupManyRequest) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

type HangupManyResponse struct {
	Id                   []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HangupManyResponse) Reset()         { *m = HangupManyResponse{} }
func (m *HangupManyResponse) String() string { return proto.CompactTextString(m) }
func (*HangupManyResponse) ProtoMessage()    {}
func (*HangupManyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{11}
}

func (m *HangupManyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HangupManyResponse.Unmarshal(m, b)
}
func (m *HangupManyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HangupManyResponse.Marshal(b, m, deterministic)
}
func (m *HangupManyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HangupManyResponse.Merge(m, src)
}
func (m *HangupManyResponse) XXX_Size() int {
	return xxx_messageInfo_HangupManyResponse.Size(m)
}
func (m *HangupManyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HangupManyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HangupManyResponse proto.InternalMessageInfo

func (m *HangupManyResponse) GetId() []string {
	if m != nil {
		return m.Id
	}
	return nil
}

type QueueRequest struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Variables            map[string]string `protobuf:"bytes,2,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	PlaybackFile         string            `protobuf:"bytes,3,opt,name=playback_file,json=playbackFile,proto3" json:"playback_file,omitempty"`
	PlaybackArgs         int32             `protobuf:"varint,4,opt,name=playback_args,json=playbackArgs,proto3" json:"playback_args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *QueueRequest) Reset()         { *m = QueueRequest{} }
func (m *QueueRequest) String() string { return proto.CompactTextString(m) }
func (*QueueRequest) ProtoMessage()    {}
func (*QueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{12}
}

func (m *QueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueRequest.Unmarshal(m, b)
}
func (m *QueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueRequest.Marshal(b, m, deterministic)
}
func (m *QueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueRequest.Merge(m, src)
}
func (m *QueueRequest) XXX_Size() int {
	return xxx_messageInfo_QueueRequest.Size(m)
}
func (m *QueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueueRequest proto.InternalMessageInfo

func (m *QueueRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueueRequest) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

func (m *QueueRequest) GetPlaybackFile() string {
	if m != nil {
		return m.PlaybackFile
	}
	return ""
}

func (m *QueueRequest) GetPlaybackArgs() int32 {
	if m != nil {
		return m.PlaybackArgs
	}
	return 0
}

type QueueResponse struct {
	Error                *ErrorExecute `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *QueueResponse) Reset()         { *m = QueueResponse{} }
func (m *QueueResponse) String() string { return proto.CompactTextString(m) }
func (*QueueResponse) ProtoMessage()    {}
func (*QueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{13}
}

func (m *QueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueResponse.Unmarshal(m, b)
}
func (m *QueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueResponse.Marshal(b, m, deterministic)
}
func (m *QueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueResponse.Merge(m, src)
}
func (m *QueueResponse) XXX_Size() int {
	return xxx_messageInfo_QueueResponse.Size(m)
}
func (m *QueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueueResponse proto.InternalMessageInfo

func (m *QueueResponse) GetError() *ErrorExecute {
	if m != nil {
		return m.Error
	}
	return nil
}

type ErrorExecute struct {
	Message              string            `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Type                 ErrorExecute_Type `protobuf:"varint,2,opt,name=type,proto3,enum=fs.ErrorExecute_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ErrorExecute) Reset()         { *m = ErrorExecute{} }
func (m *ErrorExecute) String() string { return proto.CompactTextString(m) }
func (*ErrorExecute) ProtoMessage()    {}
func (*ErrorExecute) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{14}
}

func (m *ErrorExecute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorExecute.Unmarshal(m, b)
}
func (m *ErrorExecute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorExecute.Marshal(b, m, deterministic)
}
func (m *ErrorExecute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorExecute.Merge(m, src)
}
func (m *ErrorExecute) XXX_Size() int {
	return xxx_messageInfo_ErrorExecute.Size(m)
}
func (m *ErrorExecute) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorExecute.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorExecute proto.InternalMessageInfo

func (m *ErrorExecute) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ErrorExecute) GetType() ErrorExecute_Type {
	if m != nil {
		return m.Type
	}
	return ErrorExecute_ERROR
}

type ExecuteRequest struct {
	Command              string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args                 string   `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteRequest) Reset()         { *m = ExecuteRequest{} }
func (m *ExecuteRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteRequest) ProtoMessage()    {}
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{15}
}

func (m *ExecuteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteRequest.Unmarshal(m, b)
}
func (m *ExecuteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteRequest.Merge(m, src)
}
func (m *ExecuteRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteRequest.Size(m)
}
func (m *ExecuteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteRequest proto.InternalMessageInfo

func (m *ExecuteRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *ExecuteRequest) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

type ExecuteResponse struct {
	Data                 string        `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                *ErrorExecute `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ExecuteResponse) Reset()         { *m = ExecuteResponse{} }
func (m *ExecuteResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteResponse) ProtoMessage()    {}
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{16}
}

func (m *ExecuteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteResponse.Unmarshal(m, b)
}
func (m *ExecuteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteResponse.Merge(m, src)
}
func (m *ExecuteResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteResponse.Size(m)
}
func (m *ExecuteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteResponse proto.InternalMessageInfo

func (m *ExecuteResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *ExecuteResponse) GetError() *ErrorExecute {
	if m != nil {
		return m.Error
	}
	return nil
}

type HangupRequest struct {
	Uuid                 string            `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Cause                string            `protobuf:"bytes,2,opt,name=cause,proto3" json:"cause,omitempty"`
	Reporting            bool              `protobuf:"varint,3,opt,name=reporting,proto3" json:"reporting,omitempty"`
	Variables            map[string]string `protobuf:"bytes,4,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HangupRequest) Reset()         { *m = HangupRequest{} }
func (m *HangupRequest) String() string { return proto.CompactTextString(m) }
func (*HangupRequest) ProtoMessage()    {}
func (*HangupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{17}
}

func (m *HangupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HangupRequest.Unmarshal(m, b)
}
func (m *HangupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HangupRequest.Marshal(b, m, deterministic)
}
func (m *HangupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HangupRequest.Merge(m, src)
}
func (m *HangupRequest) XXX_Size() int {
	return xxx_messageInfo_HangupRequest.Size(m)
}
func (m *HangupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HangupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HangupRequest proto.InternalMessageInfo

func (m *HangupRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *HangupRequest) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

func (m *HangupRequest) GetReporting() bool {
	if m != nil {
		return m.Reporting
	}
	return false
}

func (m *HangupRequest) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

type HangupResponse struct {
	Error                *ErrorExecute `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HangupResponse) Reset()         { *m = HangupResponse{} }
func (m *HangupResponse) String() string { return proto.CompactTextString(m) }
func (*HangupResponse) ProtoMessage()    {}
func (*HangupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{18}
}

func (m *HangupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HangupResponse.Unmarshal(m, b)
}
func (m *HangupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HangupResponse.Marshal(b, m, deterministic)
}
func (m *HangupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HangupResponse.Merge(m, src)
}
func (m *HangupResponse) XXX_Size() int {
	return xxx_messageInfo_HangupResponse.Size(m)
}
func (m *HangupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HangupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HangupResponse proto.InternalMessageInfo

func (m *HangupResponse) GetError() *ErrorExecute {
	if m != nil {
		return m.Error
	}
	return nil
}

type OriginateRequest struct {
	Variables            map[string]string             `protobuf:"bytes,1,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Endpoints            []string                      `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Strategy             OriginateRequest_Strategy     `protobuf:"varint,3,opt,name=strategy,proto3,enum=fs.OriginateRequest_Strategy" json:"strategy,omitempty"`
	Destination          string                        `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	Timeout              int32                         `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	CallerNumber         string                        `protobuf:"bytes,6,opt,name=callerNumber,proto3" json:"callerNumber,omitempty"`
	CallerName           string                        `protobuf:"bytes,7,opt,name=callerName,proto3" json:"callerName,omitempty"`
	Context              string                        `protobuf:"bytes,8,opt,name=context,proto3" json:"context,omitempty"`
	Dialplan             string                        `protobuf:"bytes,9,opt,name=dialplan,proto3" json:"dialplan,omitempty"`
	Extensions           []*OriginateRequest_Extension `protobuf:"bytes,10,rep,name=extensions,proto3" json:"extensions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *OriginateRequest) Reset()         { *m = OriginateRequest{} }
func (m *OriginateRequest) String() string { return proto.CompactTextString(m) }
func (*OriginateRequest) ProtoMessage()    {}
func (*OriginateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{19}
}

func (m *OriginateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OriginateRequest.Unmarshal(m, b)
}
func (m *OriginateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OriginateRequest.Marshal(b, m, deterministic)
}
func (m *OriginateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OriginateRequest.Merge(m, src)
}
func (m *OriginateRequest) XXX_Size() int {
	return xxx_messageInfo_OriginateRequest.Size(m)
}
func (m *OriginateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OriginateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OriginateRequest proto.InternalMessageInfo

func (m *OriginateRequest) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

func (m *OriginateRequest) GetEndpoints() []string {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *OriginateRequest) GetStrategy() OriginateRequest_Strategy {
	if m != nil {
		return m.Strategy
	}
	return OriginateRequest_FAILOVER
}

func (m *OriginateRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *OriginateRequest) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *OriginateRequest) GetCallerNumber() string {
	if m != nil {
		return m.CallerNumber
	}
	return ""
}

func (m *OriginateRequest) GetCallerName() string {
	if m != nil {
		return m.CallerName
	}
	return ""
}

func (m *OriginateRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *OriginateRequest) GetDialplan() string {
	if m != nil {
		return m.Dialplan
	}
	return ""
}

func (m *OriginateRequest) GetExtensions() []*OriginateRequest_Extension {
	if m != nil {
		return m.Extensions
	}
	return nil
}

type OriginateRequest_Extension struct {
	AppName              string   `protobuf:"bytes,1,opt,name=appName,proto3" json:"appName,omitempty"`
	Args                 string   `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OriginateRequest_Extension) Reset()         { *m = OriginateRequest_Extension{} }
func (m *OriginateRequest_Extension) String() string { return proto.CompactTextString(m) }
func (*OriginateRequest_Extension) ProtoMessage()    {}
func (*OriginateRequest_Extension) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{19, 0}
}

func (m *OriginateRequest_Extension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OriginateRequest_Extension.Unmarshal(m, b)
}
func (m *OriginateRequest_Extension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OriginateRequest_Extension.Marshal(b, m, deterministic)
}
func (m *OriginateRequest_Extension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OriginateRequest_Extension.Merge(m, src)
}
func (m *OriginateRequest_Extension) XXX_Size() int {
	return xxx_messageInfo_OriginateRequest_Extension.Size(m)
}
func (m *OriginateRequest_Extension) XXX_DiscardUnknown() {
	xxx_messageInfo_OriginateRequest_Extension.DiscardUnknown(m)
}

var xxx_messageInfo_OriginateRequest_Extension proto.InternalMessageInfo

func (m *OriginateRequest_Extension) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *OriginateRequest_Extension) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

type OriginateResponse struct {
	Uuid                 string        `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Error                *ErrorExecute `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode            int32         `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *OriginateResponse) Reset()         { *m = OriginateResponse{} }
func (m *OriginateResponse) String() string { return proto.CompactTextString(m) }
func (*OriginateResponse) ProtoMessage()    {}
func (*OriginateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{20}
}

func (m *OriginateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OriginateResponse.Unmarshal(m, b)
}
func (m *OriginateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OriginateResponse.Marshal(b, m, deterministic)
}
func (m *OriginateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OriginateResponse.Merge(m, src)
}
func (m *OriginateResponse) XXX_Size() int {
	return xxx_messageInfo_OriginateResponse.Size(m)
}
func (m *OriginateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OriginateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OriginateResponse proto.InternalMessageInfo

func (m *OriginateResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *OriginateResponse) GetError() *ErrorExecute {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *OriginateResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

type BridgeRequest struct {
	LegAId               string   `protobuf:"bytes,1,opt,name=leg_a_id,json=legAId,proto3" json:"leg_a_id,omitempty"`
	LegBId               string   `protobuf:"bytes,2,opt,name=leg_b_id,json=legBId,proto3" json:"leg_b_id,omitempty"`
	LegBReserveId        string   `protobuf:"bytes,3,opt,name=leg_b_reserve_id,json=legBReserveId,proto3" json:"leg_b_reserve_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BridgeRequest) Reset()         { *m = BridgeRequest{} }
func (m *BridgeRequest) String() string { return proto.CompactTextString(m) }
func (*BridgeRequest) ProtoMessage()    {}
func (*BridgeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{21}
}

func (m *BridgeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BridgeRequest.Unmarshal(m, b)
}
func (m *BridgeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BridgeRequest.Marshal(b, m, deterministic)
}
func (m *BridgeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BridgeRequest.Merge(m, src)
}
func (m *BridgeRequest) XXX_Size() int {
	return xxx_messageInfo_BridgeRequest.Size(m)
}
func (m *BridgeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BridgeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BridgeRequest proto.InternalMessageInfo

func (m *BridgeRequest) GetLegAId() string {
	if m != nil {
		return m.LegAId
	}
	return ""
}

func (m *BridgeRequest) GetLegBId() string {
	if m != nil {
		return m.LegBId
	}
	return ""
}

func (m *BridgeRequest) GetLegBReserveId() string {
	if m != nil {
		return m.LegBReserveId
	}
	return ""
}

type BridgeResponse struct {
	Uuid                 string        `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Error                *ErrorExecute `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BridgeResponse) Reset()         { *m = BridgeResponse{} }
func (m *BridgeResponse) String() string { return proto.CompactTextString(m) }
func (*BridgeResponse) ProtoMessage()    {}
func (*BridgeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{22}
}

func (m *BridgeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BridgeResponse.Unmarshal(m, b)
}
func (m *BridgeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BridgeResponse.Marshal(b, m, deterministic)
}
func (m *BridgeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BridgeResponse.Merge(m, src)
}
func (m *BridgeResponse) XXX_Size() int {
	return xxx_messageInfo_BridgeResponse.Size(m)
}
func (m *BridgeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BridgeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BridgeResponse proto.InternalMessageInfo

func (m *BridgeResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *BridgeResponse) GetError() *ErrorExecute {
	if m != nil {
		return m.Error
	}
	return nil
}

type SetVariablesRequest struct {
	Uuid                 string            `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Variables            map[string]string `protobuf:"bytes,2,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SetVariablesRequest) Reset()         { *m = SetVariablesRequest{} }
func (m *SetVariablesRequest) String() string { return proto.CompactTextString(m) }
func (*SetVariablesRequest) ProtoMessage()    {}
func (*SetVariablesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{23}
}

func (m *SetVariablesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetVariablesRequest.Unmarshal(m, b)
}
func (m *SetVariablesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetVariablesRequest.Marshal(b, m, deterministic)
}
func (m *SetVariablesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetVariablesRequest.Merge(m, src)
}
func (m *SetVariablesRequest) XXX_Size() int {
	return xxx_messageInfo_SetVariablesRequest.Size(m)
}
func (m *SetVariablesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetVariablesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetVariablesRequest proto.InternalMessageInfo

func (m *SetVariablesRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SetVariablesRequest) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

type SetVariablesResponse struct {
	Error                *ErrorExecute `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SetVariablesResponse) Reset()         { *m = SetVariablesResponse{} }
func (m *SetVariablesResponse) String() string { return proto.CompactTextString(m) }
func (*SetVariablesResponse) ProtoMessage()    {}
func (*SetVariablesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{24}
}

func (m *SetVariablesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetVariablesResponse.Unmarshal(m, b)
}
func (m *SetVariablesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetVariablesResponse.Marshal(b, m, deterministic)
}
func (m *SetVariablesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetVariablesResponse.Merge(m, src)
}
func (m *SetVariablesResponse) XXX_Size() int {
	return xxx_messageInfo_SetVariablesResponse.Size(m)
}
func (m *SetVariablesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetVariablesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetVariablesResponse proto.InternalMessageInfo

func (m *SetVariablesResponse) GetError() *ErrorExecute {
	if m != nil {
		return m.Error
	}
	return nil
}

type HangupMatchingVarsReqeust struct {
	Cause                string            `protobuf:"bytes,1,opt,name=cause,proto3" json:"cause,omitempty"`
	Variables            map[string]string `protobuf:"bytes,2,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HangupMatchingVarsReqeust) Reset()         { *m = HangupMatchingVarsReqeust{} }
func (m *HangupMatchingVarsReqeust) String() string { return proto.CompactTextString(m) }
func (*HangupMatchingVarsReqeust) ProtoMessage()    {}
func (*HangupMatchingVarsReqeust) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{25}
}

func (m *HangupMatchingVarsReqeust) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HangupMatchingVarsReqeust.Unmarshal(m, b)
}
func (m *HangupMatchingVarsReqeust) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HangupMatchingVarsReqeust.Marshal(b, m, deterministic)
}
func (m *HangupMatchingVarsReqeust) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HangupMatchingVarsReqeust.Merge(m, src)
}
func (m *HangupMatchingVarsReqeust) XXX_Size() int {
	return xxx_messageInfo_HangupMatchingVarsReqeust.Size(m)
}
func (m *HangupMatchingVarsReqeust) XXX_DiscardUnknown() {
	xxx_messageInfo_HangupMatchingVarsReqeust.DiscardUnknown(m)
}

var xxx_messageInfo_HangupMatchingVarsReqeust proto.InternalMessageInfo

func (m *HangupMatchingVarsReqeust) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

func (m *HangupMatchingVarsReqeust) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

type HangupMatchingVarsResponse struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HangupMatchingVarsResponse) Reset()         { *m = HangupMatchingVarsResponse{} }
func (m *HangupMatchingVarsResponse) String() string { return proto.CompactTextString(m) }
func (*HangupMatchingVarsResponse) ProtoMessage()    {}
func (*HangupMatchingVarsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{26}
}

func (m *HangupMatchingVarsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HangupMatchingVarsResponse.Unmarshal(m, b)
}
func (m *HangupMatchingVarsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HangupMatchingVarsResponse.Marshal(b, m, deterministic)
}
func (m *HangupMatchingVarsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HangupMatchingVarsResponse.Merge(m, src)
}
func (m *HangupMatchingVarsResponse) XXX_Size() int {
	return xxx_messageInfo_HangupMatchingVarsResponse.Size(m)
}
func (m *HangupMatchingVarsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HangupMatchingVarsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HangupMatchingVarsResponse proto.InternalMessageInfo

func (m *HangupMatchingVarsResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterEnum("fs.ErrorExecute_Type", ErrorExecute_Type_name, ErrorExecute_Type_value)
	proto.RegisterEnum("fs.OriginateRequest_Strategy", OriginateRequest_Strategy_name, OriginateRequest_Strategy_value)
	proto.RegisterType((*SetProfileVarRequest)(nil), "fs.SetProfileVarRequest")
	proto.RegisterMapType((map[string]string)(nil), "fs.SetProfileVarRequest.VariablesEntry")
	proto.RegisterType((*SetProfileVarResponse)(nil), "fs.SetProfileVarResponse")
	proto.RegisterType((*StopPlaybackRequest)(nil), "fs.StopPlaybackRequest")
	proto.RegisterType((*StopPlaybackResponse)(nil), "fs.StopPlaybackResponse")
	proto.RegisterType((*BridgeCallRequest)(nil), "fs.BridgeCallRequest")
	proto.RegisterMapType((map[string]string)(nil), "fs.BridgeCallRequest.VariablesEntry")
	proto.RegisterType((*BridgeCallResponse)(nil), "fs.BridgeCallResponse")
	proto.RegisterType((*HoldRequest)(nil), "fs.HoldRequest")
	proto.RegisterType((*HoldResponse)(nil), "fs.HoldResponse")
	proto.RegisterType((*UnHoldRequest)(nil), "fs.UnHoldRequest")
	proto.RegisterType((*UnHoldResponse)(nil), "fs.UnHoldResponse")
	proto.RegisterType((*HangupManyRequest)(nil), "fs.HangupManyRequest")
	proto.RegisterType((*HangupManyResponse)(nil), "fs.HangupManyResponse")
	proto.RegisterType((*QueueRequest)(nil), "fs.QueueRequest")
	proto.RegisterMapType((map[string]string)(nil), "fs.QueueRequest.VariablesEntry")
	proto.RegisterType((*QueueResponse)(nil), "fs.QueueResponse")
	proto.RegisterType((*ErrorExecute)(nil), "fs.ErrorExecute")
	proto.RegisterType((*ExecuteRequest)(nil), "fs.ExecuteRequest")
	proto.RegisterType((*ExecuteResponse)(nil), "fs.ExecuteResponse")
	proto.RegisterType((*HangupRequest)(nil), "fs.HangupRequest")
	proto.RegisterMapType((map[string]string)(nil), "fs.HangupRequest.VariablesEntry")
	proto.RegisterType((*HangupResponse)(nil), "fs.HangupResponse")
	proto.RegisterType((*OriginateRequest)(nil), "fs.OriginateRequest")
	proto.RegisterMapType((map[string]string)(nil), "fs.OriginateRequest.VariablesEntry")
	proto.RegisterType((*OriginateRequest_Extension)(nil), "fs.OriginateRequest.Extension")
	proto.RegisterType((*OriginateResponse)(nil), "fs.OriginateResponse")
	proto.RegisterType((*BridgeRequest)(nil), "fs.BridgeRequest")
	proto.RegisterType((*BridgeResponse)(nil), "fs.BridgeResponse")
	proto.RegisterType((*SetVariablesRequest)(nil), "fs.SetVariablesRequest")
	proto.RegisterMapType((map[string]string)(nil), "fs.SetVariablesRequest.VariablesEntry")
	proto.RegisterType((*SetVariablesResponse)(nil), "fs.SetVariablesResponse")
	proto.RegisterType((*HangupMatchingVarsReqeust)(nil), "fs.HangupMatchingVarsReqeust")
	proto.RegisterMapType((map[string]string)(nil), "fs.HangupMatchingVarsReqeust.VariablesEntry")
	proto.RegisterType((*HangupMatchingVarsResponse)(nil), "fs.HangupMatchingVarsResponse")
}

func init() { proto.RegisterFile("protos/fs.proto", fileDescriptor_7894a1a02fa2a211) }

var fileDescriptor_7894a1a02fa2a211 = []byte{
	// 1168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xdb, 0x4e, 0xe3, 0x46,
	0x18, 0xc6, 0x39, 0x40, 0xfc, 0x93, 0x84, 0x30, 0xc0, 0xae, 0xd7, 0x02, 0x36, 0xf2, 0x6e, 0x59,
	0xaa, 0x56, 0xa9, 0x9a, 0x56, 0xea, 0xb2, 0xda, 0x45, 0x0a, 0x34, 0x74, 0xa9, 0xa0, 0x50, 0xb3,
	0x70, 0x8b, 0x26, 0xf1, 0xe0, 0x5a, 0xeb, 0xd8, 0x5e, 0x7b, 0x8c, 0xc8, 0x7b, 0xf4, 0x2d, 0xaa,
	0x3e, 0x41, 0xaf, 0x7b, 0xd1, 0x07, 0xe8, 0x23, 0xf4, 0x3d, 0xaa, 0x99, 0xf1, 0x31, 0x71, 0xa2,
	0x45, 0x88, 0x3b, 0xff, 0xe7, 0xc3, 0xfc, 0xff, 0xcc, 0x67, 0x58, 0xf1, 0x7c, 0x97, 0xba, 0xc1,
	0x37, 0x37, 0x41, 0x87, 0x7f, 0xa1, 0xd2, 0x4d, 0xa0, 0xfd, 0x21, 0xc1, 0xfa, 0x05, 0xa1, 0xe7,
	0xbe, 0x7b, 0x63, 0xd9, 0xe4, 0x0a, 0xfb, 0x3a, 0xf9, 0x14, 0x92, 0x80, 0xa2, 0x26, 0x94, 0x2c,
	0x43, 0x91, 0xda, 0xd2, 0xae, 0xac, 0x97, 0x2c, 0x03, 0xf5, 0x41, 0xbe, 0xc5, 0xbe, 0x85, 0x07,
	0x36, 0x09, 0x94, 0x52, 0xbb, 0xbc, 0xbb, 0xdc, 0x7d, 0xd5, 0xb9, 0x09, 0x3a, 0x45, 0xc6, 0x9d,
	0xab, 0x58, 0xb3, 0xef, 0x50, 0x7f, 0xac, 0xa7, 0x96, 0xea, 0x5b, 0x68, 0xe6, 0x85, 0xa8, 0x05,
	0xe5, 0x8f, 0x64, 0x1c, 0x45, 0x62, 0x9f, 0x68, 0x1d, 0xaa, 0xb7, 0xd8, 0x0e, 0x89, 0x52, 0xe2,
	0x3c, 0x41, 0xbc, 0x29, 0xbd, 0x96, 0xb4, 0xa7, 0xb0, 0x31, 0x11, 0x2f, 0xf0, 0x5c, 0x27, 0x20,
	0xda, 0x17, 0xb0, 0x76, 0x41, 0x5d, 0xef, 0xdc, 0xc6, 0xe3, 0x01, 0x1e, 0x7e, 0x9c, 0x51, 0x84,
	0xf6, 0x04, 0xd6, 0xf3, 0x6a, 0x91, 0xf9, 0x3f, 0x12, 0xac, 0x1e, 0xf8, 0x96, 0x61, 0x92, 0x43,
	0x6c, 0xdb, 0xb1, 0xb5, 0x02, 0x35, 0x9b, 0x98, 0xd7, 0xf8, 0x3a, 0xf1, 0xb1, 0x68, 0x13, 0xb3,
	0x77, 0x6c, 0xc4, 0x92, 0x01, 0x93, 0x94, 0x12, 0xc9, 0xc1, 0xb1, 0x81, 0x0e, 0xb2, 0x6d, 0x2a,
	0xf3, 0x36, 0xbd, 0x64, 0x6d, 0x9a, 0xf2, 0xfe, 0x68, 0x3d, 0x7a, 0x0b, 0x28, 0x1b, 0x4c, 0x54,
	0x88, 0x76, 0xa0, 0x4a, 0x7c, 0xdf, 0xf5, 0xb9, 0x8f, 0xe5, 0x6e, 0x8b, 0xe5, 0xd4, 0x67, 0x8c,
	0xfe, 0x1d, 0x19, 0x86, 0x94, 0xe8, 0x42, 0xac, 0x6d, 0xc1, 0xf2, 0x7b, 0xd7, 0x36, 0x26, 0x1b,
	0x58, 0x8e, 0x1a, 0xb8, 0x0d, 0x75, 0x21, 0x8e, 0xdc, 0x4e, 0xca, 0x9f, 0x43, 0xe3, 0xd2, 0x99,
	0xe7, 0xa0, 0x0d, 0xcd, 0x58, 0x61, 0x86, 0x8b, 0x3d, 0x58, 0x7d, 0x8f, 0x1d, 0x33, 0xf4, 0x4e,
	0xb1, 0x33, 0x9e, 0xe1, 0x86, 0x95, 0x3f, 0xc4, 0x61, 0x90, 0x94, 0xcf, 0x09, 0xed, 0x25, 0xa0,
	0xac, 0xe9, 0x8c, 0x00, 0xff, 0x49, 0x50, 0xff, 0x35, 0x24, 0x21, 0x99, 0x35, 0xea, 0xef, 0xa6,
	0x47, 0xfd, 0x39, 0xeb, 0x57, 0xd6, 0x68, 0xf6, 0xf1, 0xa1, 0x17, 0xd0, 0xf0, 0xa2, 0x01, 0xbb,
	0x66, 0x73, 0xaa, 0x94, 0xb9, 0xe7, 0x7a, 0xcc, 0x3c, 0xb2, 0x6c, 0x92, 0x53, 0xc2, 0xbe, 0x19,
	0x28, 0x95, 0xb6, 0xb4, 0x5b, 0x4d, 0x95, 0x7a, 0xbe, 0xf9, 0xd0, 0x41, 0xf8, 0x01, 0x1a, 0x51,
	0xc6, 0xf7, 0x9c, 0x81, 0x4f, 0x50, 0xcf, 0xb2, 0x91, 0x02, 0x4b, 0x23, 0x12, 0x04, 0xd8, 0x24,
	0x51, 0xe0, 0x98, 0x44, 0x5f, 0x42, 0x85, 0x8e, 0x3d, 0x11, 0xbb, 0xd9, 0xdd, 0x98, 0x74, 0xd8,
	0xf9, 0x30, 0xf6, 0x88, 0xce, 0x55, 0xb4, 0x4d, 0xa8, 0x30, 0x0a, 0xc9, 0x50, 0xed, 0xeb, 0xfa,
	0x99, 0xde, 0x5a, 0x60, 0x9f, 0x97, 0x17, 0xbd, 0x9f, 0xfa, 0x2d, 0x49, 0xdb, 0x87, 0x66, 0x9c,
	0x44, 0xb2, 0x7c, 0x4b, 0x43, 0x77, 0x34, 0xc2, 0x4e, 0x7c, 0x32, 0x31, 0x89, 0x10, 0x54, 0x78,
	0xc7, 0x44, 0xc1, 0xfc, 0x5b, 0x3b, 0x85, 0x95, 0xc4, 0x3e, 0xaa, 0x16, 0x41, 0xc5, 0xc0, 0x14,
	0x47, 0xd6, 0xfc, 0x3b, 0xed, 0x40, 0x69, 0x7e, 0x07, 0xfe, 0x95, 0xa0, 0x21, 0x26, 0x29, 0x4e,
	0x07, 0x41, 0x25, 0x0c, 0x93, 0x29, 0xe1, 0xdf, 0xc5, 0x43, 0x88, 0x36, 0x41, 0xf6, 0x89, 0xe7,
	0xfa, 0xd4, 0x72, 0x4c, 0x7e, 0xf4, 0x35, 0x3d, 0x65, 0xa0, 0xfd, 0xec, 0x6c, 0x55, 0xf8, 0x6c,
	0xb5, 0x59, 0x16, 0xb9, 0x68, 0x8f, 0x76, 0x37, 0xbc, 0x86, 0x66, 0x1c, 0xe8, 0x9e, 0x33, 0xf1,
	0x77, 0x05, 0x5a, 0x67, 0xbe, 0x65, 0x5a, 0x0e, 0x4e, 0xcf, 0xa8, 0x97, 0x2d, 0x46, 0xe2, 0xc5,
	0xbc, 0x60, 0x0e, 0x26, 0x15, 0xe7, 0x2c, 0xcb, 0x26, 0xc8, 0xc4, 0x31, 0x3c, 0xd7, 0x72, 0xa8,
	0xd8, 0x35, 0x59, 0x4f, 0x19, 0x68, 0x0f, 0x6a, 0x01, 0xf5, 0x31, 0x25, 0xe6, 0x98, 0xb7, 0xb2,
	0xd9, 0xdd, 0x2a, 0xf4, 0x7f, 0x11, 0x29, 0xe9, 0x89, 0x3a, 0x6a, 0xc3, 0xb2, 0x41, 0x02, 0xca,
	0xd4, 0x2c, 0xd7, 0xe1, 0xeb, 0x25, 0xeb, 0x59, 0x16, 0x9b, 0x30, 0x6a, 0x8d, 0x88, 0x1b, 0x52,
	0xa5, 0xca, 0x97, 0x2f, 0x26, 0x91, 0x06, 0xf5, 0x21, 0xb6, 0x6d, 0xe2, 0xff, 0x12, 0x8e, 0x06,
	0xc4, 0x57, 0x16, 0xc5, 0x02, 0x67, 0x79, 0x68, 0x1b, 0x20, 0xa2, 0xf1, 0x88, 0x28, 0x4b, 0x5c,
	0x23, 0xc3, 0x11, 0xf3, 0xeb, 0x50, 0x72, 0x47, 0x95, 0x5a, 0x3c, 0xbf, 0x9c, 0x44, 0x2a, 0xd4,
	0x0c, 0x0b, 0xdb, 0x9e, 0x8d, 0x1d, 0x45, 0xe6, 0xa2, 0x84, 0x46, 0xfb, 0x00, 0xe4, 0x8e, 0x12,
	0x27, 0xb0, 0x5c, 0x27, 0x50, 0x80, 0xb7, 0x74, 0xbb, 0xb0, 0xe4, 0x7e, 0xac, 0xa6, 0x67, 0x2c,
	0xd4, 0x3d, 0x90, 0x13, 0x01, 0x4b, 0x01, 0x7b, 0x1e, 0xcf, 0x2f, 0x5a, 0xa1, 0x88, 0x2c, 0x5a,
	0xa1, 0x07, 0x4e, 0xd6, 0x0e, 0xd4, 0xe2, 0x43, 0x40, 0x75, 0xa8, 0x1d, 0xf5, 0x8e, 0x4f, 0xce,
	0xae, 0xfa, 0x6c, 0xcb, 0xeb, 0x50, 0x3b, 0xbd, 0x3c, 0xf9, 0x70, 0x7c, 0x7e, 0xc2, 0x16, 0xdd,
	0x81, 0xd5, 0x4c, 0x29, 0xe9, 0xaa, 0x4e, 0x2d, 0xd7, 0x67, 0xae, 0x2a, 0xda, 0x02, 0xe0, 0x1f,
	0xd7, 0x43, 0xd7, 0x10, 0x57, 0x6d, 0x55, 0x97, 0x39, 0xe7, 0xd0, 0x35, 0x88, 0x66, 0x43, 0x43,
	0xbc, 0x86, 0x0f, 0x79, 0xd4, 0x5f, 0x41, 0x4b, 0x48, 0x7c, 0x12, 0x10, 0xff, 0x96, 0x30, 0x0d,
	0x71, 0xa9, 0x37, 0x98, 0x86, 0x2e, 0xb8, 0xc7, 0x86, 0x76, 0x02, 0xcd, 0x38, 0xda, 0xc3, 0x4b,
	0xd3, 0xfe, 0x94, 0x60, 0xed, 0x82, 0xd0, 0xe4, 0x54, 0xe6, 0xdd, 0x45, 0x3f, 0x4e, 0xbf, 0x59,
	0x3b, 0x11, 0x3c, 0x9b, 0xb4, 0x7f, 0xb4, 0xdb, 0x65, 0x9f, 0x43, 0xc9, 0x4c, 0xb8, 0x7b, 0xde,
	0x31, 0x7f, 0x49, 0xf0, 0x2c, 0x7e, 0xbf, 0xe9, 0xf0, 0x37, 0xcb, 0x31, 0xaf, 0xb0, 0xcf, 0xb2,
	0x26, 0x61, 0x40, 0xd3, 0xdb, 0x56, 0xca, 0xde, 0xb6, 0x3f, 0x4f, 0xd7, 0xfd, 0x75, 0x7a, 0x9f,
	0x16, 0xf8, 0x79, 0xb4, 0xea, 0xbb, 0xa0, 0x16, 0x05, 0x8d, 0x7a, 0xc0, 0xb2, 0x77, 0x43, 0x87,
	0x72, 0x5f, 0x55, 0x5d, 0x10, 0xdd, 0xdf, 0x17, 0xa1, 0xdc, 0xf3, 0x2c, 0xf4, 0x06, 0xe4, 0x64,
	0x2b, 0xd0, 0x7a, 0xd1, 0xbe, 0xab, 0x1b, 0x13, 0xdc, 0x08, 0xb9, 0x2e, 0xa0, 0xef, 0x61, 0x29,
	0x7e, 0xa8, 0x11, 0xef, 0x6c, 0xee, 0x1d, 0x55, 0xd7, 0x72, 0xbc, 0xc4, 0xea, 0x10, 0xea, 0xd9,
	0xb3, 0x42, 0x4f, 0x67, 0x0c, 0x8b, 0xaa, 0x4c, 0x0b, 0x12, 0x27, 0xdf, 0xc2, 0xa2, 0x18, 0x77,
	0xb4, 0x9a, 0x62, 0xdc, 0xd8, 0x10, 0x65, 0x59, 0x89, 0xc9, 0x3b, 0x80, 0x14, 0x9d, 0xa2, 0x8d,
	0x42, 0x68, 0xac, 0x3e, 0x99, 0x64, 0xe7, 0xd2, 0xce, 0x00, 0xf8, 0x28, 0xed, 0x69, 0xe4, 0x1f,
	0xa5, 0x5d, 0x84, 0xf5, 0x79, 0xda, 0xe2, 0xa4, 0x44, 0xda, 0xb9, 0xa7, 0x57, 0xa4, 0x9d, 0x7f,
	0x24, 0xb5, 0x05, 0x74, 0x99, 0x22, 0xcb, 0xf4, 0x70, 0xd1, 0xd6, 0xdc, 0x49, 0x53, 0xb7, 0x67,
	0x89, 0x13, 0xb7, 0x1d, 0xa8, 0x72, 0x88, 0x86, 0x5a, 0x93, 0xf8, 0x52, 0x5d, 0xcd, 0x70, 0xb2,
	0xdd, 0x4b, 0x01, 0xae, 0xe8, 0xde, 0x14, 0x56, 0x16, 0xdd, 0x9b, 0xc6, 0xc1, 0xda, 0x02, 0xfa,
	0x0a, 0x2a, 0x0c, 0x7a, 0xa3, 0x15, 0xae, 0x91, 0xa2, 0x74, 0xb5, 0x95, 0x32, 0xb2, 0x5d, 0x12,
	0x48, 0x5d, 0x74, 0x29, 0x07, 0xeb, 0x45, 0x97, 0xf2, 0x40, 0x5e, 0x5b, 0x40, 0x47, 0xd0, 0xc8,
	0xfd, 0x9e, 0x21, 0x65, 0xd6, 0x1f, 0xa2, 0xfa, 0xac, 0x40, 0x12, 0xfb, 0x19, 0x2c, 0xf2, 0xff,
	0xd3, 0xef, 0xfe, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x15, 0xbe, 0xd5, 0xd8, 0xb2, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiClient interface {
	Originate(ctx context.Context, in *OriginateRequest, opts ...grpc.CallOption) (*OriginateResponse, error)
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	SetVariables(ctx context.Context, in *SetVariablesRequest, opts ...grpc.CallOption) (*SetVariablesResponse, error)
	Bridge(ctx context.Context, in *BridgeRequest, opts ...grpc.CallOption) (*BridgeResponse, error)
	BridgeCall(ctx context.Context, in *BridgeCallRequest, opts ...grpc.CallOption) (*BridgeCallResponse, error)
	StopPlayback(ctx context.Context, in *StopPlaybackRequest, opts ...grpc.CallOption) (*StopPlaybackResponse, error)
	Hangup(ctx context.Context, in *HangupRequest, opts ...grpc.CallOption) (*HangupResponse, error)
	HangupMatchingVars(ctx context.Context, in *HangupMatchingVarsReqeust, opts ...grpc.CallOption) (*HangupMatchingVarsResponse, error)
	Queue(ctx context.Context, in *QueueRequest, opts ...grpc.CallOption) (*QueueResponse, error)
	HangupMany(ctx context.Context, in *HangupManyRequest, opts ...grpc.CallOption) (*HangupManyResponse, error)
	Hold(ctx context.Context, in *HoldRequest, opts ...grpc.CallOption) (*HoldResponse, error)
	UnHold(ctx context.Context, in *UnHoldRequest, opts ...grpc.CallOption) (*UnHoldResponse, error)
	SetProfileVar(ctx context.Context, in *SetProfileVarRequest, opts ...grpc.CallOption) (*SetProfileVarResponse, error)
}

type apiClient struct {
	cc *grpc.ClientConn
}

func NewApiClient(cc *grpc.ClientConn) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) Originate(ctx context.Context, in *OriginateRequest, opts ...grpc.CallOption) (*OriginateResponse, error) {
	out := new(OriginateResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/Originate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) SetVariables(ctx context.Context, in *SetVariablesRequest, opts ...grpc.CallOption) (*SetVariablesResponse, error) {
	out := new(SetVariablesResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/SetVariables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Bridge(ctx context.Context, in *BridgeRequest, opts ...grpc.CallOption) (*BridgeResponse, error) {
	out := new(BridgeResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/Bridge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) BridgeCall(ctx context.Context, in *BridgeCallRequest, opts ...grpc.CallOption) (*BridgeCallResponse, error) {
	out := new(BridgeCallResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/BridgeCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) StopPlayback(ctx context.Context, in *StopPlaybackRequest, opts ...grpc.CallOption) (*StopPlaybackResponse, error) {
	out := new(StopPlaybackResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/StopPlayback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Hangup(ctx context.Context, in *HangupRequest, opts ...grpc.CallOption) (*HangupResponse, error) {
	out := new(HangupResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/Hangup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) HangupMatchingVars(ctx context.Context, in *HangupMatchingVarsReqeust, opts ...grpc.CallOption) (*HangupMatchingVarsResponse, error) {
	out := new(HangupMatchingVarsResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/HangupMatchingVars", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Queue(ctx context.Context, in *QueueRequest, opts ...grpc.CallOption) (*QueueResponse, error) {
	out := new(QueueResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/Queue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) HangupMany(ctx context.Context, in *HangupManyRequest, opts ...grpc.CallOption) (*HangupManyResponse, error) {
	out := new(HangupManyResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/HangupMany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Hold(ctx context.Context, in *HoldRequest, opts ...grpc.CallOption) (*HoldResponse, error) {
	out := new(HoldResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/Hold", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) UnHold(ctx context.Context, in *UnHoldRequest, opts ...grpc.CallOption) (*UnHoldResponse, error) {
	out := new(UnHoldResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/UnHold", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) SetProfileVar(ctx context.Context, in *SetProfileVarRequest, opts ...grpc.CallOption) (*SetProfileVarResponse, error) {
	out := new(SetProfileVarResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/SetProfileVar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
type ApiServer interface {
	Originate(context.Context, *OriginateRequest) (*OriginateResponse, error)
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	SetVariables(context.Context, *SetVariablesRequest) (*SetVariablesResponse, error)
	Bridge(context.Context, *BridgeRequest) (*BridgeResponse, error)
	BridgeCall(context.Context, *BridgeCallRequest) (*BridgeCallResponse, error)
	StopPlayback(context.Context, *StopPlaybackRequest) (*StopPlaybackResponse, error)
	Hangup(context.Context, *HangupRequest) (*HangupResponse, error)
	HangupMatchingVars(context.Context, *HangupMatchingVarsReqeust) (*HangupMatchingVarsResponse, error)
	Queue(context.Context, *QueueRequest) (*QueueResponse, error)
	HangupMany(context.Context, *HangupManyRequest) (*HangupManyResponse, error)
	Hold(context.Context, *HoldRequest) (*HoldResponse, error)
	UnHold(context.Context, *UnHoldRequest) (*UnHoldResponse, error)
	SetProfileVar(context.Context, *SetProfileVarRequest) (*SetProfileVarResponse, error)
}

// UnimplementedApiServer can be embedded to have forward compatible implementations.
type UnimplementedApiServer struct {
}

func (*UnimplementedApiServer) Originate(ctx context.Context, req *OriginateRequest) (*OriginateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Originate not implemented")
}
func (*UnimplementedApiServer) Execute(ctx context.Context, req *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (*UnimplementedApiServer) SetVariables(ctx context.Context, req *SetVariablesRequest) (*SetVariablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVariables not implemented")
}
func (*UnimplementedApiServer) Bridge(ctx context.Context, req *BridgeRequest) (*BridgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bridge not implemented")
}
func (*UnimplementedApiServer) BridgeCall(ctx context.Context, req *BridgeCallRequest) (*BridgeCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BridgeCall not implemented")
}
func (*UnimplementedApiServer) StopPlayback(ctx context.Context, req *StopPlaybackRequest) (*StopPlaybackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopPlayback not implemented")
}
func (*UnimplementedApiServer) Hangup(ctx context.Context, req *HangupRequest) (*HangupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hangup not implemented")
}
func (*UnimplementedApiServer) HangupMatchingVars(ctx context.Context, req *HangupMatchingVarsReqeust) (*HangupMatchingVarsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HangupMatchingVars not implemented")
}
func (*UnimplementedApiServer) Queue(ctx context.Context, req *QueueRequest) (*QueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Queue not implemented")
}
func (*UnimplementedApiServer) HangupMany(ctx context.Context, req *HangupManyRequest) (*HangupManyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HangupMany not implemented")
}
func (*UnimplementedApiServer) Hold(ctx context.Context, req *HoldRequest) (*HoldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hold not implemented")
}
func (*UnimplementedApiServer) UnHold(ctx context.Context, req *UnHoldRequest) (*UnHoldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnHold not implemented")
}
func (*UnimplementedApiServer) SetProfileVar(ctx context.Context, req *SetProfileVarRequest) (*SetProfileVarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetProfileVar not implemented")
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_Originate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OriginateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Originate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/Originate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Originate(ctx, req.(*OriginateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_SetVariables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVariablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).SetVariables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/SetVariables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).SetVariables(ctx, req.(*SetVariablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Bridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Bridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/Bridge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Bridge(ctx, req.(*BridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_BridgeCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BridgeCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).BridgeCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/BridgeCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).BridgeCall(ctx, req.(*BridgeCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_StopPlayback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopPlaybackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).StopPlayback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/StopPlayback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).StopPlayback(ctx, req.(*StopPlaybackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Hangup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HangupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Hangup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/Hangup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Hangup(ctx, req.(*HangupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_HangupMatchingVars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HangupMatchingVarsReqeust)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).HangupMatchingVars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/HangupMatchingVars",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).HangupMatchingVars(ctx, req.(*HangupMatchingVarsReqeust))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Queue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Queue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/Queue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Queue(ctx, req.(*QueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_HangupMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HangupManyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).HangupMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/HangupMany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).HangupMany(ctx, req.(*HangupManyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Hold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HoldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Hold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/Hold",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Hold(ctx, req.(*HoldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_UnHold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnHoldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).UnHold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/UnHold",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).UnHold(ctx, req.(*UnHoldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_SetProfileVar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetProfileVarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).SetProfileVar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/SetProfileVar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).SetProfileVar(ctx, req.(*SetProfileVarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fs.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Originate",
			Handler:    _Api_Originate_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _Api_Execute_Handler,
		},
		{
			MethodName: "SetVariables",
			Handler:    _Api_SetVariables_Handler,
		},
		{
			MethodName: "Bridge",
			Handler:    _Api_Bridge_Handler,
		},
		{
			MethodName: "BridgeCall",
			Handler:    _Api_BridgeCall_Handler,
		},
		{
			MethodName: "StopPlayback",
			Handler:    _Api_StopPlayback_Handler,
		},
		{
			MethodName: "Hangup",
			Handler:    _Api_Hangup_Handler,
		},
		{
			MethodName: "HangupMatchingVars",
			Handler:    _Api_HangupMatchingVars_Handler,
		},
		{
			MethodName: "Queue",
			Handler:    _Api_Queue_Handler,
		},
		{
			MethodName: "HangupMany",
			Handler:    _Api_HangupMany_Handler,
		},
		{
			MethodName: "Hold",
			Handler:    _Api_Hold_Handler,
		},
		{
			MethodName: "UnHold",
			Handler:    _Api_UnHold_Handler,
		},
		{
			MethodName: "SetProfileVar",
			Handler:    _Api_SetProfileVar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/fs.proto",
}
