// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/fs.proto

package fs

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorExecute_Type int32

const (
	ErrorExecute_ERROR ErrorExecute_Type = 0
	ErrorExecute_USAGE ErrorExecute_Type = 1
)

var ErrorExecute_Type_name = map[int32]string{
	0: "ERROR",
	1: "USAGE",
}

var ErrorExecute_Type_value = map[string]int32{
	"ERROR": 0,
	"USAGE": 1,
}

func (x ErrorExecute_Type) String() string {
	return proto.EnumName(ErrorExecute_Type_name, int32(x))
}

func (ErrorExecute_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{0, 0}
}

type OriginateRequest_Strategy int32

const (
	OriginateRequest_FAILOVER OriginateRequest_Strategy = 0
	OriginateRequest_MULTIPLE OriginateRequest_Strategy = 1
)

var OriginateRequest_Strategy_name = map[int32]string{
	0: "FAILOVER",
	1: "MULTIPLE",
}

var OriginateRequest_Strategy_value = map[string]int32{
	"FAILOVER": 0,
	"MULTIPLE": 1,
}

func (x OriginateRequest_Strategy) String() string {
	return proto.EnumName(OriginateRequest_Strategy_name, int32(x))
}

func (OriginateRequest_Strategy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{5, 0}
}

type ErrorExecute struct {
	Message              string            `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Type                 ErrorExecute_Type `protobuf:"varint,2,opt,name=type,proto3,enum=fs.ErrorExecute_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ErrorExecute) Reset()         { *m = ErrorExecute{} }
func (m *ErrorExecute) String() string { return proto.CompactTextString(m) }
func (*ErrorExecute) ProtoMessage()    {}
func (*ErrorExecute) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{0}
}

func (m *ErrorExecute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorExecute.Unmarshal(m, b)
}
func (m *ErrorExecute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorExecute.Marshal(b, m, deterministic)
}
func (m *ErrorExecute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorExecute.Merge(m, src)
}
func (m *ErrorExecute) XXX_Size() int {
	return xxx_messageInfo_ErrorExecute.Size(m)
}
func (m *ErrorExecute) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorExecute.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorExecute proto.InternalMessageInfo

func (m *ErrorExecute) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ErrorExecute) GetType() ErrorExecute_Type {
	if m != nil {
		return m.Type
	}
	return ErrorExecute_ERROR
}

type ExecuteRequest struct {
	Command              string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args                 string   `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteRequest) Reset()         { *m = ExecuteRequest{} }
func (m *ExecuteRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteRequest) ProtoMessage()    {}
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{1}
}

func (m *ExecuteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteRequest.Unmarshal(m, b)
}
func (m *ExecuteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteRequest.Merge(m, src)
}
func (m *ExecuteRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteRequest.Size(m)
}
func (m *ExecuteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteRequest proto.InternalMessageInfo

func (m *ExecuteRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *ExecuteRequest) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

type ExecuteResponse struct {
	Data                 string        `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                *ErrorExecute `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ExecuteResponse) Reset()         { *m = ExecuteResponse{} }
func (m *ExecuteResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteResponse) ProtoMessage()    {}
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{2}
}

func (m *ExecuteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteResponse.Unmarshal(m, b)
}
func (m *ExecuteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteResponse.Merge(m, src)
}
func (m *ExecuteResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteResponse.Size(m)
}
func (m *ExecuteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteResponse proto.InternalMessageInfo

func (m *ExecuteResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *ExecuteResponse) GetError() *ErrorExecute {
	if m != nil {
		return m.Error
	}
	return nil
}

type HangupRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Cause                string   `protobuf:"bytes,2,opt,name=cause,proto3" json:"cause,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HangupRequest) Reset()         { *m = HangupRequest{} }
func (m *HangupRequest) String() string { return proto.CompactTextString(m) }
func (*HangupRequest) ProtoMessage()    {}
func (*HangupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{3}
}

func (m *HangupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HangupRequest.Unmarshal(m, b)
}
func (m *HangupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HangupRequest.Marshal(b, m, deterministic)
}
func (m *HangupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HangupRequest.Merge(m, src)
}
func (m *HangupRequest) XXX_Size() int {
	return xxx_messageInfo_HangupRequest.Size(m)
}
func (m *HangupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HangupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HangupRequest proto.InternalMessageInfo

func (m *HangupRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *HangupRequest) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

type HangupResponse struct {
	Error                *ErrorExecute `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HangupResponse) Reset()         { *m = HangupResponse{} }
func (m *HangupResponse) String() string { return proto.CompactTextString(m) }
func (*HangupResponse) ProtoMessage()    {}
func (*HangupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{4}
}

func (m *HangupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HangupResponse.Unmarshal(m, b)
}
func (m *HangupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HangupResponse.Marshal(b, m, deterministic)
}
func (m *HangupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HangupResponse.Merge(m, src)
}
func (m *HangupResponse) XXX_Size() int {
	return xxx_messageInfo_HangupResponse.Size(m)
}
func (m *HangupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HangupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HangupResponse proto.InternalMessageInfo

func (m *HangupResponse) GetError() *ErrorExecute {
	if m != nil {
		return m.Error
	}
	return nil
}

type OriginateRequest struct {
	Variables            map[string]string             `protobuf:"bytes,1,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Endpoints            []string                      `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Strategy             OriginateRequest_Strategy     `protobuf:"varint,3,opt,name=strategy,proto3,enum=fs.OriginateRequest_Strategy" json:"strategy,omitempty"`
	Destination          string                        `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	Timeout              int32                         `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	CallerNumber         string                        `protobuf:"bytes,6,opt,name=callerNumber,proto3" json:"callerNumber,omitempty"`
	CallerName           string                        `protobuf:"bytes,7,opt,name=callerName,proto3" json:"callerName,omitempty"`
	Context              string                        `protobuf:"bytes,8,opt,name=context,proto3" json:"context,omitempty"`
	Dialplan             string                        `protobuf:"bytes,9,opt,name=dialplan,proto3" json:"dialplan,omitempty"`
	Extensions           []*OriginateRequest_Extension `protobuf:"bytes,10,rep,name=extensions,proto3" json:"extensions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *OriginateRequest) Reset()         { *m = OriginateRequest{} }
func (m *OriginateRequest) String() string { return proto.CompactTextString(m) }
func (*OriginateRequest) ProtoMessage()    {}
func (*OriginateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{5}
}

func (m *OriginateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OriginateRequest.Unmarshal(m, b)
}
func (m *OriginateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OriginateRequest.Marshal(b, m, deterministic)
}
func (m *OriginateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OriginateRequest.Merge(m, src)
}
func (m *OriginateRequest) XXX_Size() int {
	return xxx_messageInfo_OriginateRequest.Size(m)
}
func (m *OriginateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OriginateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OriginateRequest proto.InternalMessageInfo

func (m *OriginateRequest) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

func (m *OriginateRequest) GetEndpoints() []string {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *OriginateRequest) GetStrategy() OriginateRequest_Strategy {
	if m != nil {
		return m.Strategy
	}
	return OriginateRequest_FAILOVER
}

func (m *OriginateRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *OriginateRequest) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *OriginateRequest) GetCallerNumber() string {
	if m != nil {
		return m.CallerNumber
	}
	return ""
}

func (m *OriginateRequest) GetCallerName() string {
	if m != nil {
		return m.CallerName
	}
	return ""
}

func (m *OriginateRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *OriginateRequest) GetDialplan() string {
	if m != nil {
		return m.Dialplan
	}
	return ""
}

func (m *OriginateRequest) GetExtensions() []*OriginateRequest_Extension {
	if m != nil {
		return m.Extensions
	}
	return nil
}

type OriginateRequest_Extension struct {
	AppName              string   `protobuf:"bytes,1,opt,name=appName,proto3" json:"appName,omitempty"`
	Args                 string   `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OriginateRequest_Extension) Reset()         { *m = OriginateRequest_Extension{} }
func (m *OriginateRequest_Extension) String() string { return proto.CompactTextString(m) }
func (*OriginateRequest_Extension) ProtoMessage()    {}
func (*OriginateRequest_Extension) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{5, 0}
}

func (m *OriginateRequest_Extension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OriginateRequest_Extension.Unmarshal(m, b)
}
func (m *OriginateRequest_Extension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OriginateRequest_Extension.Marshal(b, m, deterministic)
}
func (m *OriginateRequest_Extension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OriginateRequest_Extension.Merge(m, src)
}
func (m *OriginateRequest_Extension) XXX_Size() int {
	return xxx_messageInfo_OriginateRequest_Extension.Size(m)
}
func (m *OriginateRequest_Extension) XXX_DiscardUnknown() {
	xxx_messageInfo_OriginateRequest_Extension.DiscardUnknown(m)
}

var xxx_messageInfo_OriginateRequest_Extension proto.InternalMessageInfo

func (m *OriginateRequest_Extension) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *OriginateRequest_Extension) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

type OriginateResponse struct {
	Uuid                 string        `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Error                *ErrorExecute `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode            int32         `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *OriginateResponse) Reset()         { *m = OriginateResponse{} }
func (m *OriginateResponse) String() string { return proto.CompactTextString(m) }
func (*OriginateResponse) ProtoMessage()    {}
func (*OriginateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{6}
}

func (m *OriginateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OriginateResponse.Unmarshal(m, b)
}
func (m *OriginateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OriginateResponse.Marshal(b, m, deterministic)
}
func (m *OriginateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OriginateResponse.Merge(m, src)
}
func (m *OriginateResponse) XXX_Size() int {
	return xxx_messageInfo_OriginateResponse.Size(m)
}
func (m *OriginateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OriginateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OriginateResponse proto.InternalMessageInfo

func (m *OriginateResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *OriginateResponse) GetError() *ErrorExecute {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *OriginateResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

type BridgeRequest struct {
	LegAId               string   `protobuf:"bytes,1,opt,name=leg_a_id,json=legAId,proto3" json:"leg_a_id,omitempty"`
	LegBId               string   `protobuf:"bytes,2,opt,name=leg_b_id,json=legBId,proto3" json:"leg_b_id,omitempty"`
	LegBReserveId        string   `protobuf:"bytes,3,opt,name=leg_b_reserve_id,json=legBReserveId,proto3" json:"leg_b_reserve_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BridgeRequest) Reset()         { *m = BridgeRequest{} }
func (m *BridgeRequest) String() string { return proto.CompactTextString(m) }
func (*BridgeRequest) ProtoMessage()    {}
func (*BridgeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{7}
}

func (m *BridgeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BridgeRequest.Unmarshal(m, b)
}
func (m *BridgeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BridgeRequest.Marshal(b, m, deterministic)
}
func (m *BridgeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BridgeRequest.Merge(m, src)
}
func (m *BridgeRequest) XXX_Size() int {
	return xxx_messageInfo_BridgeRequest.Size(m)
}
func (m *BridgeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BridgeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BridgeRequest proto.InternalMessageInfo

func (m *BridgeRequest) GetLegAId() string {
	if m != nil {
		return m.LegAId
	}
	return ""
}

func (m *BridgeRequest) GetLegBId() string {
	if m != nil {
		return m.LegBId
	}
	return ""
}

func (m *BridgeRequest) GetLegBReserveId() string {
	if m != nil {
		return m.LegBReserveId
	}
	return ""
}

type BridgeResponse struct {
	Uuid                 string        `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Error                *ErrorExecute `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BridgeResponse) Reset()         { *m = BridgeResponse{} }
func (m *BridgeResponse) String() string { return proto.CompactTextString(m) }
func (*BridgeResponse) ProtoMessage()    {}
func (*BridgeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{8}
}

func (m *BridgeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BridgeResponse.Unmarshal(m, b)
}
func (m *BridgeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BridgeResponse.Marshal(b, m, deterministic)
}
func (m *BridgeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BridgeResponse.Merge(m, src)
}
func (m *BridgeResponse) XXX_Size() int {
	return xxx_messageInfo_BridgeResponse.Size(m)
}
func (m *BridgeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BridgeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BridgeResponse proto.InternalMessageInfo

func (m *BridgeResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *BridgeResponse) GetError() *ErrorExecute {
	if m != nil {
		return m.Error
	}
	return nil
}

type SetVariablesReqeust struct {
	Uuid                 string            `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Variables            map[string]string `protobuf:"bytes,2,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SetVariablesReqeust) Reset()         { *m = SetVariablesReqeust{} }
func (m *SetVariablesReqeust) String() string { return proto.CompactTextString(m) }
func (*SetVariablesReqeust) ProtoMessage()    {}
func (*SetVariablesReqeust) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{9}
}

func (m *SetVariablesReqeust) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetVariablesReqeust.Unmarshal(m, b)
}
func (m *SetVariablesReqeust) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetVariablesReqeust.Marshal(b, m, deterministic)
}
func (m *SetVariablesReqeust) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetVariablesReqeust.Merge(m, src)
}
func (m *SetVariablesReqeust) XXX_Size() int {
	return xxx_messageInfo_SetVariablesReqeust.Size(m)
}
func (m *SetVariablesReqeust) XXX_DiscardUnknown() {
	xxx_messageInfo_SetVariablesReqeust.DiscardUnknown(m)
}

var xxx_messageInfo_SetVariablesReqeust proto.InternalMessageInfo

func (m *SetVariablesReqeust) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SetVariablesReqeust) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

type SetVariablesResponse struct {
	Error                *ErrorExecute `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SetVariablesResponse) Reset()         { *m = SetVariablesResponse{} }
func (m *SetVariablesResponse) String() string { return proto.CompactTextString(m) }
func (*SetVariablesResponse) ProtoMessage()    {}
func (*SetVariablesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{10}
}

func (m *SetVariablesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetVariablesResponse.Unmarshal(m, b)
}
func (m *SetVariablesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetVariablesResponse.Marshal(b, m, deterministic)
}
func (m *SetVariablesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetVariablesResponse.Merge(m, src)
}
func (m *SetVariablesResponse) XXX_Size() int {
	return xxx_messageInfo_SetVariablesResponse.Size(m)
}
func (m *SetVariablesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetVariablesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetVariablesResponse proto.InternalMessageInfo

func (m *SetVariablesResponse) GetError() *ErrorExecute {
	if m != nil {
		return m.Error
	}
	return nil
}

type HangupMatchingVarsReqeust struct {
	Cause                string            `protobuf:"bytes,1,opt,name=cause,proto3" json:"cause,omitempty"`
	Variables            map[string]string `protobuf:"bytes,2,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HangupMatchingVarsReqeust) Reset()         { *m = HangupMatchingVarsReqeust{} }
func (m *HangupMatchingVarsReqeust) String() string { return proto.CompactTextString(m) }
func (*HangupMatchingVarsReqeust) ProtoMessage()    {}
func (*HangupMatchingVarsReqeust) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{11}
}

func (m *HangupMatchingVarsReqeust) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HangupMatchingVarsReqeust.Unmarshal(m, b)
}
func (m *HangupMatchingVarsReqeust) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HangupMatchingVarsReqeust.Marshal(b, m, deterministic)
}
func (m *HangupMatchingVarsReqeust) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HangupMatchingVarsReqeust.Merge(m, src)
}
func (m *HangupMatchingVarsReqeust) XXX_Size() int {
	return xxx_messageInfo_HangupMatchingVarsReqeust.Size(m)
}
func (m *HangupMatchingVarsReqeust) XXX_DiscardUnknown() {
	xxx_messageInfo_HangupMatchingVarsReqeust.DiscardUnknown(m)
}

var xxx_messageInfo_HangupMatchingVarsReqeust proto.InternalMessageInfo

func (m *HangupMatchingVarsReqeust) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

func (m *HangupMatchingVarsReqeust) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

type HangupMatchingVarsResponse struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HangupMatchingVarsResponse) Reset()         { *m = HangupMatchingVarsResponse{} }
func (m *HangupMatchingVarsResponse) String() string { return proto.CompactTextString(m) }
func (*HangupMatchingVarsResponse) ProtoMessage()    {}
func (*HangupMatchingVarsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7894a1a02fa2a211, []int{12}
}

func (m *HangupMatchingVarsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HangupMatchingVarsResponse.Unmarshal(m, b)
}
func (m *HangupMatchingVarsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HangupMatchingVarsResponse.Marshal(b, m, deterministic)
}
func (m *HangupMatchingVarsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HangupMatchingVarsResponse.Merge(m, src)
}
func (m *HangupMatchingVarsResponse) XXX_Size() int {
	return xxx_messageInfo_HangupMatchingVarsResponse.Size(m)
}
func (m *HangupMatchingVarsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HangupMatchingVarsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HangupMatchingVarsResponse proto.InternalMessageInfo

func (m *HangupMatchingVarsResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterEnum("fs.ErrorExecute_Type", ErrorExecute_Type_name, ErrorExecute_Type_value)
	proto.RegisterEnum("fs.OriginateRequest_Strategy", OriginateRequest_Strategy_name, OriginateRequest_Strategy_value)
	proto.RegisterType((*ErrorExecute)(nil), "fs.ErrorExecute")
	proto.RegisterType((*ExecuteRequest)(nil), "fs.ExecuteRequest")
	proto.RegisterType((*ExecuteResponse)(nil), "fs.ExecuteResponse")
	proto.RegisterType((*HangupRequest)(nil), "fs.HangupRequest")
	proto.RegisterType((*HangupResponse)(nil), "fs.HangupResponse")
	proto.RegisterType((*OriginateRequest)(nil), "fs.OriginateRequest")
	proto.RegisterMapType((map[string]string)(nil), "fs.OriginateRequest.VariablesEntry")
	proto.RegisterType((*OriginateRequest_Extension)(nil), "fs.OriginateRequest.Extension")
	proto.RegisterType((*OriginateResponse)(nil), "fs.OriginateResponse")
	proto.RegisterType((*BridgeRequest)(nil), "fs.BridgeRequest")
	proto.RegisterType((*BridgeResponse)(nil), "fs.BridgeResponse")
	proto.RegisterType((*SetVariablesReqeust)(nil), "fs.SetVariablesReqeust")
	proto.RegisterMapType((map[string]string)(nil), "fs.SetVariablesReqeust.VariablesEntry")
	proto.RegisterType((*SetVariablesResponse)(nil), "fs.SetVariablesResponse")
	proto.RegisterType((*HangupMatchingVarsReqeust)(nil), "fs.HangupMatchingVarsReqeust")
	proto.RegisterMapType((map[string]string)(nil), "fs.HangupMatchingVarsReqeust.VariablesEntry")
	proto.RegisterType((*HangupMatchingVarsResponse)(nil), "fs.HangupMatchingVarsResponse")
}

func init() { proto.RegisterFile("protos/fs.proto", fileDescriptor_7894a1a02fa2a211) }

var fileDescriptor_7894a1a02fa2a211 = []byte{
	// 817 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x5b, 0x6f, 0xeb, 0x44,
	0x10, 0xae, 0x73, 0x6b, 0x3c, 0x4d, 0x73, 0x72, 0xf6, 0xf4, 0x08, 0x63, 0xb5, 0x55, 0x64, 0xa4,
	0x12, 0x24, 0x14, 0x44, 0xe0, 0xa1, 0xad, 0x50, 0xa5, 0xb4, 0x04, 0x08, 0x4a, 0x29, 0xda, 0x5e,
	0x5e, 0xab, 0x4d, 0x3c, 0x35, 0x16, 0x8e, 0xed, 0x7a, 0xd7, 0x55, 0xf3, 0xa3, 0xf8, 0x05, 0x3c,
	0xf3, 0xa3, 0x78, 0x43, 0xbb, 0xbe, 0xc4, 0x6e, 0x92, 0x0a, 0x54, 0xf1, 0xb6, 0x33, 0xf3, 0x7d,
	0x33, 0xb3, 0x73, 0xf1, 0x1a, 0xde, 0x85, 0x51, 0x20, 0x02, 0xfe, 0xd5, 0x03, 0xef, 0xab, 0x13,
	0xa9, 0x3c, 0x70, 0xeb, 0x11, 0x5a, 0xa3, 0x28, 0x0a, 0xa2, 0xd1, 0x33, 0xce, 0x62, 0x81, 0xc4,
	0x80, 0xed, 0x39, 0x72, 0xce, 0x1c, 0x34, 0xb4, 0xae, 0xd6, 0xd3, 0x69, 0x26, 0x92, 0x2f, 0xa0,
	0x26, 0x16, 0x21, 0x1a, 0x95, 0xae, 0xd6, 0x6b, 0x0f, 0x3e, 0xf6, 0x1f, 0x78, 0xbf, 0xc8, 0xec,
	0xdf, 0x2c, 0x42, 0xa4, 0x0a, 0x62, 0xed, 0x43, 0x4d, 0x4a, 0x44, 0x87, 0xfa, 0x88, 0xd2, 0x2b,
	0xda, 0xd9, 0x92, 0xc7, 0xdb, 0xeb, 0xe1, 0x8f, 0xa3, 0x8e, 0x66, 0x9d, 0x41, 0x3b, 0xe5, 0x50,
	0x7c, 0x8c, 0x91, 0x0b, 0x19, 0x74, 0x16, 0xcc, 0xe7, 0xcc, 0xb7, 0xb3, 0xa0, 0xa9, 0x48, 0x08,
	0xd4, 0x58, 0xe4, 0x70, 0x15, 0x54, 0xa7, 0xea, 0x6c, 0x5d, 0xc2, 0xbb, 0x9c, 0xcf, 0xc3, 0xc0,
	0xe7, 0x28, 0x61, 0x36, 0x13, 0x2c, 0x65, 0xab, 0x33, 0x39, 0x82, 0x3a, 0xca, 0xfc, 0x14, 0x77,
	0x67, 0xd0, 0x79, 0x99, 0x30, 0x4d, 0xcc, 0xd6, 0x09, 0xec, 0xfe, 0xc4, 0x7c, 0x27, 0x0e, 0xb3,
	0x6c, 0x08, 0xd4, 0xe2, 0xd8, 0xcd, 0x52, 0x51, 0x67, 0xb2, 0x07, 0xf5, 0x19, 0x8b, 0x39, 0xa6,
	0x89, 0x24, 0x82, 0x75, 0x0c, 0xed, 0x8c, 0x9a, 0x26, 0x92, 0x07, 0xd5, 0x5e, 0x0f, 0xfa, 0x57,
	0x0d, 0x3a, 0x57, 0x91, 0xeb, 0xb8, 0x3e, 0x5b, 0x96, 0x61, 0x08, 0xfa, 0x13, 0x8b, 0x5c, 0x36,
	0xf5, 0x90, 0x1b, 0x5a, 0xb7, 0xda, 0xdb, 0x19, 0x7c, 0x26, 0x1d, 0xbc, 0x04, 0xf6, 0xef, 0x32,
	0xd4, 0xc8, 0x17, 0xd1, 0x82, 0x2e, 0x59, 0x64, 0x1f, 0x74, 0xf4, 0xed, 0x30, 0x70, 0x7d, 0x21,
	0x8b, 0x56, 0xed, 0xe9, 0x74, 0xa9, 0x20, 0x27, 0xd0, 0xe4, 0x22, 0x62, 0x02, 0x9d, 0x85, 0x51,
	0x55, 0x6d, 0x3c, 0x58, 0xeb, 0xff, 0x3a, 0x05, 0xd1, 0x1c, 0x4e, 0xba, 0xb0, 0x63, 0x23, 0x17,
	0x12, 0xe6, 0x06, 0xbe, 0x51, 0x53, 0x65, 0x28, 0xaa, 0x64, 0x13, 0x85, 0x3b, 0xc7, 0x20, 0x16,
	0x46, 0xbd, 0xab, 0xf5, 0xea, 0x34, 0x13, 0x89, 0x05, 0xad, 0x19, 0xf3, 0x3c, 0x8c, 0x7e, 0x89,
	0xe7, 0x53, 0x8c, 0x8c, 0x86, 0x22, 0x97, 0x74, 0xe4, 0x10, 0x20, 0x95, 0xd9, 0x1c, 0x8d, 0x6d,
	0x85, 0x28, 0x68, 0x92, 0x11, 0xf1, 0x05, 0x3e, 0x0b, 0xa3, 0x99, 0x8d, 0x88, 0x12, 0x89, 0x09,
	0x4d, 0xdb, 0x65, 0x5e, 0xe8, 0x31, 0xdf, 0xd0, 0x95, 0x29, 0x97, 0xc9, 0x19, 0x00, 0x3e, 0x0b,
	0xf4, 0xb9, 0x1b, 0xf8, 0xdc, 0x00, 0x55, 0xd2, 0xc3, 0xb5, 0x57, 0x1e, 0x65, 0x30, 0x5a, 0x60,
	0x98, 0x27, 0xa0, 0xe7, 0x06, 0x99, 0x02, 0x0b, 0x43, 0x95, 0x5f, 0x3a, 0xa5, 0xa9, 0xb8, 0x6e,
	0x4a, 0xcd, 0xef, 0xa0, 0x5d, 0x6e, 0x13, 0xe9, 0x40, 0xf5, 0x77, 0x5c, 0xa4, 0x5c, 0x79, 0x94,
	0x53, 0xf5, 0xc4, 0xbc, 0x38, 0x9f, 0x2a, 0x25, 0x9c, 0x56, 0x8e, 0x35, 0xeb, 0x08, 0x9a, 0x59,
	0x13, 0x48, 0x0b, 0x9a, 0x3f, 0x0c, 0xc7, 0x93, 0xab, 0xbb, 0x91, 0x5c, 0xa4, 0x16, 0x34, 0x2f,
	0x6f, 0x27, 0x37, 0xe3, 0x5f, 0x27, 0x72, 0x97, 0x7c, 0x78, 0x5f, 0xb8, 0xca, 0x72, 0x1b, 0x56,
	0x06, 0xf8, 0x5f, 0x6e, 0x03, 0x39, 0x00, 0x50, 0x87, 0xfb, 0x59, 0x60, 0xa3, 0x1a, 0x92, 0x3a,
	0xd5, 0x95, 0xe6, 0x22, 0xb0, 0xd1, 0xf2, 0x60, 0xf7, 0x3c, 0x72, 0x6d, 0xa7, 0xb0, 0xba, 0x4d,
	0x0f, 0x9d, 0x7b, 0x76, 0x9f, 0xc7, 0x6b, 0x78, 0xe8, 0x0c, 0xc7, 0x76, 0x66, 0x99, 0x4a, 0x4b,
	0x25, 0xb7, 0x9c, 0x8f, 0x6d, 0xf2, 0x39, 0x74, 0x12, 0x4b, 0x84, 0x1c, 0xa3, 0x27, 0x94, 0x88,
	0xaa, 0x42, 0xec, 0x4a, 0x04, 0x4d, 0xb4, 0x63, 0xdb, 0x9a, 0x40, 0x3b, 0x8b, 0xf6, 0xf6, 0xab,
	0x59, 0x7f, 0x68, 0xf0, 0xe1, 0x1a, 0x45, 0xde, 0x15, 0x8a, 0x8f, 0x18, 0x6f, 0xd8, 0xf7, 0xef,
	0x8b, 0xab, 0x58, 0x51, 0x73, 0x73, 0x24, 0xfd, 0xae, 0xe1, 0x6f, 0xde, 0xc6, 0x37, 0xce, 0xc0,
	0x19, 0xec, 0x95, 0xc3, 0xfd, 0xc7, 0x6f, 0xcc, 0x9f, 0x1a, 0x7c, 0x9a, 0x7c, 0x9e, 0x2e, 0x99,
	0x98, 0xfd, 0xe6, 0xfa, 0xce, 0x1d, 0x8b, 0xf2, 0x5b, 0xe7, 0x5f, 0x34, 0xad, 0xf0, 0x45, 0x23,
	0x3f, 0xaf, 0xde, 0xfb, 0x4b, 0xe9, 0x7f, 0xa3, 0x9f, 0xff, 0xed, 0xf6, 0x03, 0x30, 0xd7, 0x05,
	0x4d, 0x6b, 0x20, 0xb3, 0x0f, 0x62, 0x5f, 0x28, 0x5f, 0x75, 0x9a, 0x08, 0x83, 0xbf, 0x2b, 0x50,
	0x1d, 0x86, 0x2e, 0x39, 0x05, 0x3d, 0xdf, 0x0a, 0xb2, 0xb7, 0x6e, 0xdf, 0xcd, 0x8f, 0x2f, 0xb4,
	0x89, 0x5f, 0x6b, 0x8b, 0x7c, 0x0b, 0xdb, 0xd9, 0x5b, 0x48, 0x54, 0x65, 0x4b, 0x4f, 0x95, 0xf9,
	0xa1, 0xa4, 0xcb, 0x59, 0x17, 0xd0, 0x2a, 0xf6, 0x8a, 0x7c, 0xb2, 0x61, 0x58, 0x4c, 0x63, 0xd5,
	0x90, 0x3b, 0xf9, 0x1a, 0x1a, 0xc9, 0xb8, 0x93, 0xf7, 0x12, 0x55, 0x5a, 0x34, 0x93, 0x14, 0x55,
	0x45, 0x4a, 0x52, 0xa5, 0x84, 0x52, 0x7a, 0xc8, 0x12, 0x4a, 0xf9, 0x81, 0xb2, 0xb6, 0xc8, 0x2d,
	0x90, 0xd5, 0xc2, 0x92, 0x83, 0x57, 0xbb, 0x6c, 0x1e, 0x6e, 0x32, 0x67, 0x6e, 0xa7, 0x0d, 0xf5,
	0x4f, 0xf1, 0xcd, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf5, 0xc2, 0x8e, 0x1a, 0x66, 0x08, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiClient interface {
	Originate(ctx context.Context, in *OriginateRequest, opts ...grpc.CallOption) (*OriginateResponse, error)
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	SetVariables(ctx context.Context, in *SetVariablesReqeust, opts ...grpc.CallOption) (*SetVariablesResponse, error)
	Bridge(ctx context.Context, in *BridgeRequest, opts ...grpc.CallOption) (*BridgeResponse, error)
	Hangup(ctx context.Context, in *HangupRequest, opts ...grpc.CallOption) (*HangupResponse, error)
	HangupMatchingVars(ctx context.Context, in *HangupMatchingVarsReqeust, opts ...grpc.CallOption) (*HangupMatchingVarsResponse, error)
}

type apiClient struct {
	cc *grpc.ClientConn
}

func NewApiClient(cc *grpc.ClientConn) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) Originate(ctx context.Context, in *OriginateRequest, opts ...grpc.CallOption) (*OriginateResponse, error) {
	out := new(OriginateResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/Originate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) SetVariables(ctx context.Context, in *SetVariablesReqeust, opts ...grpc.CallOption) (*SetVariablesResponse, error) {
	out := new(SetVariablesResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/SetVariables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Bridge(ctx context.Context, in *BridgeRequest, opts ...grpc.CallOption) (*BridgeResponse, error) {
	out := new(BridgeResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/Bridge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Hangup(ctx context.Context, in *HangupRequest, opts ...grpc.CallOption) (*HangupResponse, error) {
	out := new(HangupResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/Hangup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) HangupMatchingVars(ctx context.Context, in *HangupMatchingVarsReqeust, opts ...grpc.CallOption) (*HangupMatchingVarsResponse, error) {
	out := new(HangupMatchingVarsResponse)
	err := c.cc.Invoke(ctx, "/fs.Api/HangupMatchingVars", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
type ApiServer interface {
	Originate(context.Context, *OriginateRequest) (*OriginateResponse, error)
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	SetVariables(context.Context, *SetVariablesReqeust) (*SetVariablesResponse, error)
	Bridge(context.Context, *BridgeRequest) (*BridgeResponse, error)
	Hangup(context.Context, *HangupRequest) (*HangupResponse, error)
	HangupMatchingVars(context.Context, *HangupMatchingVarsReqeust) (*HangupMatchingVarsResponse, error)
}

// UnimplementedApiServer can be embedded to have forward compatible implementations.
type UnimplementedApiServer struct {
}

func (*UnimplementedApiServer) Originate(ctx context.Context, req *OriginateRequest) (*OriginateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Originate not implemented")
}
func (*UnimplementedApiServer) Execute(ctx context.Context, req *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (*UnimplementedApiServer) SetVariables(ctx context.Context, req *SetVariablesReqeust) (*SetVariablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVariables not implemented")
}
func (*UnimplementedApiServer) Bridge(ctx context.Context, req *BridgeRequest) (*BridgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bridge not implemented")
}
func (*UnimplementedApiServer) Hangup(ctx context.Context, req *HangupRequest) (*HangupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hangup not implemented")
}
func (*UnimplementedApiServer) HangupMatchingVars(ctx context.Context, req *HangupMatchingVarsReqeust) (*HangupMatchingVarsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HangupMatchingVars not implemented")
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_Originate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OriginateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Originate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/Originate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Originate(ctx, req.(*OriginateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_SetVariables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVariablesReqeust)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).SetVariables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/SetVariables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).SetVariables(ctx, req.(*SetVariablesReqeust))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Bridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Bridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/Bridge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Bridge(ctx, req.(*BridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Hangup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HangupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Hangup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/Hangup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Hangup(ctx, req.(*HangupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_HangupMatchingVars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HangupMatchingVarsReqeust)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).HangupMatchingVars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/HangupMatchingVars",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).HangupMatchingVars(ctx, req.(*HangupMatchingVarsReqeust))
	}
	return interceptor(ctx, in, info, handler)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fs.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Originate",
			Handler:    _Api_Originate_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _Api_Execute_Handler,
		},
		{
			MethodName: "SetVariables",
			Handler:    _Api_SetVariables_Handler,
		},
		{
			MethodName: "Bridge",
			Handler:    _Api_Bridge_Handler,
		},
		{
			MethodName: "Hangup",
			Handler:    _Api_Hangup_Handler,
		},
		{
			MethodName: "HangupMatchingVars",
			Handler:    _Api_HangupMatchingVars_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/fs.proto",
}
