// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/fs.proto

/*
Package fs is a generated protocol buffer package.

It is generated from these files:
	protos/fs.proto

It has these top-level messages:
	ErrorExecute
	ExecuteRequest
	ExecuteResponse
	HangupRequest
	HangupResponse
	OriginateRequest
	OriginateResponse
*/
package fs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorExecute_Type int32

const (
	ErrorExecute_ERROR ErrorExecute_Type = 0
	ErrorExecute_USAGE ErrorExecute_Type = 1
)

var ErrorExecute_Type_name = map[int32]string{
	0: "ERROR",
	1: "USAGE",
}
var ErrorExecute_Type_value = map[string]int32{
	"ERROR": 0,
	"USAGE": 1,
}

func (x ErrorExecute_Type) String() string {
	return proto.EnumName(ErrorExecute_Type_name, int32(x))
}
func (ErrorExecute_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type ErrorExecute struct {
	Message string            `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Type    ErrorExecute_Type `protobuf:"varint,2,opt,name=type,enum=fs.ErrorExecute_Type" json:"type,omitempty"`
}

func (m *ErrorExecute) Reset()                    { *m = ErrorExecute{} }
func (m *ErrorExecute) String() string            { return proto.CompactTextString(m) }
func (*ErrorExecute) ProtoMessage()               {}
func (*ErrorExecute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ErrorExecute) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ErrorExecute) GetType() ErrorExecute_Type {
	if m != nil {
		return m.Type
	}
	return ErrorExecute_ERROR
}

type ExecuteRequest struct {
	Command string `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	Args    string `protobuf:"bytes,2,opt,name=args" json:"args,omitempty"`
}

func (m *ExecuteRequest) Reset()                    { *m = ExecuteRequest{} }
func (m *ExecuteRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecuteRequest) ProtoMessage()               {}
func (*ExecuteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ExecuteRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *ExecuteRequest) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

type ExecuteResponse struct {
	Data  string        `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Error *ErrorExecute `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *ExecuteResponse) Reset()                    { *m = ExecuteResponse{} }
func (m *ExecuteResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecuteResponse) ProtoMessage()               {}
func (*ExecuteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ExecuteResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *ExecuteResponse) GetError() *ErrorExecute {
	if m != nil {
		return m.Error
	}
	return nil
}

type HangupRequest struct {
	Uuid  string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Cause string `protobuf:"bytes,2,opt,name=cause" json:"cause,omitempty"`
}

func (m *HangupRequest) Reset()                    { *m = HangupRequest{} }
func (m *HangupRequest) String() string            { return proto.CompactTextString(m) }
func (*HangupRequest) ProtoMessage()               {}
func (*HangupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HangupRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *HangupRequest) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

type HangupResponse struct {
	Error *ErrorExecute `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *HangupResponse) Reset()                    { *m = HangupResponse{} }
func (m *HangupResponse) String() string            { return proto.CompactTextString(m) }
func (*HangupResponse) ProtoMessage()               {}
func (*HangupResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HangupResponse) GetError() *ErrorExecute {
	if m != nil {
		return m.Error
	}
	return nil
}

type OriginateRequest struct {
	Variables    map[string]string `protobuf:"bytes,1,rep,name=variables" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Endpoints    []string          `protobuf:"bytes,2,rep,name=endpoints" json:"endpoints,omitempty"`
	Destination  string            `protobuf:"bytes,3,opt,name=destination" json:"destination,omitempty"`
	Timeout      int32             `protobuf:"varint,4,opt,name=timeout" json:"timeout,omitempty"`
	CallerNumber string            `protobuf:"bytes,5,opt,name=callerNumber" json:"callerNumber,omitempty"`
	CallerName   string            `protobuf:"bytes,6,opt,name=callerName" json:"callerName,omitempty"`
	Context      string            `protobuf:"bytes,7,opt,name=context" json:"context,omitempty"`
	Dialplan     string            `protobuf:"bytes,8,opt,name=dialplan" json:"dialplan,omitempty"`
}

func (m *OriginateRequest) Reset()                    { *m = OriginateRequest{} }
func (m *OriginateRequest) String() string            { return proto.CompactTextString(m) }
func (*OriginateRequest) ProtoMessage()               {}
func (*OriginateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *OriginateRequest) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

func (m *OriginateRequest) GetEndpoints() []string {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *OriginateRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *OriginateRequest) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *OriginateRequest) GetCallerNumber() string {
	if m != nil {
		return m.CallerNumber
	}
	return ""
}

func (m *OriginateRequest) GetCallerName() string {
	if m != nil {
		return m.CallerName
	}
	return ""
}

func (m *OriginateRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *OriginateRequest) GetDialplan() string {
	if m != nil {
		return m.Dialplan
	}
	return ""
}

type OriginateResponse struct {
	Uuid  string        `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Error *ErrorExecute `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *OriginateResponse) Reset()                    { *m = OriginateResponse{} }
func (m *OriginateResponse) String() string            { return proto.CompactTextString(m) }
func (*OriginateResponse) ProtoMessage()               {}
func (*OriginateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *OriginateResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *OriginateResponse) GetError() *ErrorExecute {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*ErrorExecute)(nil), "fs.ErrorExecute")
	proto.RegisterType((*ExecuteRequest)(nil), "fs.ExecuteRequest")
	proto.RegisterType((*ExecuteResponse)(nil), "fs.ExecuteResponse")
	proto.RegisterType((*HangupRequest)(nil), "fs.HangupRequest")
	proto.RegisterType((*HangupResponse)(nil), "fs.HangupResponse")
	proto.RegisterType((*OriginateRequest)(nil), "fs.OriginateRequest")
	proto.RegisterType((*OriginateResponse)(nil), "fs.OriginateResponse")
	proto.RegisterEnum("fs.ErrorExecute_Type", ErrorExecute_Type_name, ErrorExecute_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Api service

type ApiClient interface {
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	Hangup(ctx context.Context, in *HangupRequest, opts ...grpc.CallOption) (*HangupResponse, error)
	Originate(ctx context.Context, in *OriginateRequest, opts ...grpc.CallOption) (*OriginateResponse, error)
}

type apiClient struct {
	cc *grpc.ClientConn
}

func NewApiClient(cc *grpc.ClientConn) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := grpc.Invoke(ctx, "/fs.Api/Execute", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Hangup(ctx context.Context, in *HangupRequest, opts ...grpc.CallOption) (*HangupResponse, error) {
	out := new(HangupResponse)
	err := grpc.Invoke(ctx, "/fs.Api/Hangup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Originate(ctx context.Context, in *OriginateRequest, opts ...grpc.CallOption) (*OriginateResponse, error) {
	out := new(OriginateResponse)
	err := grpc.Invoke(ctx, "/fs.Api/Originate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Api service

type ApiServer interface {
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	Hangup(context.Context, *HangupRequest) (*HangupResponse, error)
	Originate(context.Context, *OriginateRequest) (*OriginateResponse, error)
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Hangup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HangupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Hangup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/Hangup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Hangup(ctx, req.(*HangupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Originate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OriginateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Originate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.Api/Originate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Originate(ctx, req.(*OriginateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fs.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _Api_Execute_Handler,
		},
		{
			MethodName: "Hangup",
			Handler:    _Api_Hangup_Handler,
		},
		{
			MethodName: "Originate",
			Handler:    _Api_Originate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/fs.proto",
}

func init() { proto.RegisterFile("protos/fs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 504 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x5d, 0xfa, 0xb9, 0xdc, 0x8e, 0xae, 0xbb, 0x6c, 0x92, 0x55, 0x4d, 0xa8, 0x0a, 0x12, 0x2a,
	0x2f, 0x45, 0x14, 0x1e, 0xc6, 0x84, 0x90, 0xfa, 0x50, 0xc1, 0x0b, 0x54, 0x32, 0x1f, 0xef, 0x6e,
	0x7b, 0x5b, 0x45, 0x24, 0x4e, 0x66, 0x3b, 0xd3, 0xfa, 0x97, 0xf8, 0x63, 0xfc, 0x0d, 0x64, 0x37,
	0x4e, 0x3f, 0x40, 0x68, 0x6f, 0xf7, 0x9c, 0x9c, 0x93, 0x7b, 0xed, 0x73, 0x0d, 0xe7, 0xb9, 0xca,
	0x4c, 0xa6, 0x5f, 0xad, 0xf4, 0xc8, 0x55, 0x58, 0x5b, 0xe9, 0xe8, 0x0e, 0xce, 0xa6, 0x4a, 0x65,
	0x6a, 0xfa, 0x40, 0x8b, 0xc2, 0x10, 0x32, 0x68, 0xa7, 0xa4, 0xb5, 0x58, 0x13, 0x0b, 0x06, 0xc1,
	0x30, 0xe4, 0x1e, 0xe2, 0x4b, 0x68, 0x98, 0x4d, 0x4e, 0xac, 0x36, 0x08, 0x86, 0xdd, 0xf1, 0xd5,
	0x68, 0xa5, 0x47, 0xfb, 0xce, 0xd1, 0xb7, 0x4d, 0x4e, 0xdc, 0x49, 0xa2, 0x6b, 0x68, 0x58, 0x84,
	0x21, 0x34, 0xa7, 0x9c, 0xcf, 0x78, 0xef, 0xc4, 0x96, 0xdf, 0xbf, 0x4e, 0x3e, 0x4e, 0x7b, 0x41,
	0xf4, 0x01, 0xba, 0xa5, 0x87, 0xd3, 0x5d, 0x41, 0xda, 0xd8, 0xa6, 0x8b, 0x2c, 0x4d, 0x85, 0x5c,
	0xfa, 0xa6, 0x25, 0x44, 0x84, 0x86, 0x50, 0x6b, 0xed, 0x9a, 0x86, 0xdc, 0xd5, 0xd1, 0x67, 0x38,
	0xaf, 0xfc, 0x3a, 0xcf, 0xa4, 0x26, 0x2b, 0x5b, 0x0a, 0x23, 0x4a, 0xb7, 0xab, 0xf1, 0x05, 0x34,
	0xc9, 0xce, 0xe7, 0xbc, 0x9d, 0x71, 0xef, 0x78, 0x60, 0xbe, 0xfd, 0x1c, 0xbd, 0x83, 0x27, 0x9f,
	0x84, 0x5c, 0x17, 0xb9, 0x9f, 0x06, 0xa1, 0x51, 0x14, 0xb1, 0x1f, 0xc5, 0xd5, 0x78, 0x09, 0xcd,
	0x85, 0x28, 0x34, 0x95, 0x83, 0x6c, 0x41, 0x74, 0x03, 0x5d, 0x6f, 0x2d, 0x07, 0xa9, 0x9a, 0x06,
	0xff, 0x6f, 0xfa, 0xbb, 0x06, 0xbd, 0x99, 0x8a, 0xd7, 0xb1, 0x14, 0xbb, 0x6b, 0x98, 0x40, 0x78,
	0x2f, 0x54, 0x2c, 0xe6, 0x09, 0x69, 0x16, 0x0c, 0xea, 0xc3, 0xce, 0xf8, 0xb9, 0xfd, 0xc1, 0xb1,
	0x70, 0xf4, 0xc3, 0xab, 0xa6, 0xd2, 0xa8, 0x0d, 0xdf, 0xb9, 0xf0, 0x1a, 0x42, 0x92, 0xcb, 0x3c,
	0x8b, 0xa5, 0xb1, 0x97, 0x56, 0x1f, 0x86, 0x7c, 0x47, 0xe0, 0x00, 0x3a, 0x4b, 0xd2, 0xc6, 0xfe,
	0x2b, 0xce, 0x24, 0xab, 0xbb, 0xb3, 0xec, 0x53, 0x36, 0x09, 0x13, 0xa7, 0x94, 0x15, 0x86, 0x35,
	0x06, 0xc1, 0xb0, 0xc9, 0x3d, 0xc4, 0x08, 0xce, 0x16, 0x22, 0x49, 0x48, 0x7d, 0x29, 0xd2, 0x39,
	0x29, 0xd6, 0x74, 0xe6, 0x03, 0x0e, 0x9f, 0x01, 0x94, 0x58, 0xa4, 0xc4, 0x5a, 0x4e, 0xb1, 0xc7,
	0x6c, 0x73, 0x96, 0x86, 0x1e, 0x0c, 0x6b, 0xfb, 0x9c, 0x1d, 0xc4, 0x3e, 0x9c, 0x2e, 0x63, 0x91,
	0xe4, 0x89, 0x90, 0xec, 0xd4, 0x7d, 0xaa, 0x70, 0xff, 0x3d, 0x74, 0x0f, 0x0f, 0x8c, 0x3d, 0xa8,
	0xff, 0xa4, 0x4d, 0x19, 0x90, 0x2d, 0x6d, 0x3e, 0xf7, 0x22, 0x29, 0xaa, 0x7c, 0x1c, 0xb8, 0xad,
	0xdd, 0x04, 0xd1, 0x0c, 0x2e, 0xf6, 0xee, 0x6f, 0xb7, 0x2f, 0x7f, 0x45, 0xfc, 0xc8, 0x7d, 0x19,
	0xff, 0x0a, 0xa0, 0x3e, 0xc9, 0x63, 0x7c, 0x0b, 0x6d, 0xff, 0x68, 0xd0, 0x69, 0x0f, 0x76, 0xba,
	0xff, 0xf4, 0x80, 0xdb, 0xf6, 0x8d, 0x4e, 0xf0, 0x35, 0xb4, 0xb6, 0x2b, 0x83, 0x17, 0x56, 0x70,
	0xb0, 0x79, 0x7d, 0xdc, 0xa7, 0x2a, 0xcb, 0x2d, 0x84, 0xd5, 0x09, 0xf0, 0xf2, 0x5f, 0x0b, 0xd1,
	0xbf, 0x3a, 0x62, 0xbd, 0x77, 0xde, 0x72, 0x2f, 0xfd, 0xcd, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x7a, 0x59, 0x91, 0xf1, 0xfc, 0x03, 0x00, 0x00,
}
