create table if not exists call_center.cc_skill_group
(
    id          bigint generated by default as identity
        constraint cc_skill_group_pk primary key,
    domain_id   bigint      not null
        constraint cc_skill_group_domain_fk references directory.wbt_domain (dc) on delete cascade,
    name        varchar     not null,
    description varchar     default ''::character varying not null,
    created_at  timestamptz,
    created_by  bigint
        constraint cc_skill_group_created_by_fk references directory.wbt_user (id) on delete set null,
    updated_at  timestamptz,
    updated_by  bigint
        constraint cc_skill_group_updated_by_fk references directory.wbt_user (id) on delete set null
);

create index if not exists cc_skill_group_domain_id_name_index
    on call_center.cc_skill_group (domain_id, name);

create unique index if not exists cc_skill_group_domain_id_udx
    on call_center.cc_skill_group (id, domain_id);

create table if not exists call_center.cc_skill_group_acl
(
    id      bigint generated by default as identity
        constraint cc_skill_group_acl_pk primary key,
    dc      bigint   not null
        constraint cc_skill_group_acl_domain_fk references directory.wbt_domain (dc) on delete cascade,
    grantor bigint
        constraint cc_skill_group_acl_grantor_id_fk references directory.wbt_auth (id) on delete set null,
    object  bigint   not null,
    subject bigint   not null,
    access  smallint default 0 not null,
    constraint cc_skill_group_acl_object_fk
        foreign key (object, dc) references call_center.cc_skill_group (id, domain_id) on delete cascade,
    constraint cc_skill_group_acl_grantor_fk
        foreign key (grantor, dc) references directory.wbt_auth (id, dc) on update cascade on delete cascade,
    constraint cc_skill_group_acl_subject_fk
        foreign key (subject, dc) references directory.wbt_auth (id, dc) on delete cascade
);

create index if not exists cc_skill_group_acl_grantor_idx
    on call_center.cc_skill_group_acl (grantor);
create unique index if not exists cc_skill_group_acl_object_subject_udx
    on call_center.cc_skill_group_acl (object, subject) include (access);
create unique index if not exists cc_skill_group_acl_subject_object_udx
    on call_center.cc_skill_group_acl (subject, object) include (access);

drop trigger if exists cc_skill_group_set_rbac_acl on call_center.cc_skill_group;
create trigger cc_skill_group_set_rbac_acl
    after insert on call_center.cc_skill_group
    for each row
execute function call_center.tg_obj_default_rbac('cc_skill_group');

create table if not exists call_center.cc_skill_in_group
(
    id             bigint generated by default as identity
        constraint cc_skill_in_group_pk primary key,
    skill_group_id bigint   not null
        constraint cc_skill_in_group_group_fk references call_center.cc_skill_group (id) on delete cascade,
    skill_id       integer  not null
        constraint cc_skill_in_group_skill_fk references call_center.cc_skill (id) on delete cascade,
    capacity       smallint default 0 not null,
    created_at     timestamptz default now() not null,
    created_by     bigint
        constraint cc_skill_in_group_created_by_fk references directory.wbt_user (id) on delete set null,
    updated_at     timestamptz default now() not null,
    updated_by     bigint
        constraint cc_skill_in_group_updated_by_fk references directory.wbt_user (id) on delete set null
);

create unique index if not exists cc_skill_in_group_group_id_skill_id_udx
    on call_center.cc_skill_in_group (skill_group_id, skill_id);

create table if not exists call_center.cc_agent_in_skill_group
(
    id             bigint generated by default as identity
        constraint cc_agent_in_skill_group_pk primary key,
    skill_group_id bigint  not null
        constraint cc_agent_in_skill_group_group_fk references call_center.cc_skill_group (id) on delete cascade,
    agent_id       integer not null
        constraint cc_agent_in_skill_group_agent_fk references call_center.cc_agent (id) on delete cascade,
    created_at     timestamptz default now() not null,
    created_by     bigint
        constraint cc_agent_in_skill_group_created_by_fk references directory.wbt_user (id) on delete set null,
    updated_at     timestamptz default now() not null,
    updated_by     bigint
        constraint cc_agent_in_skill_group_updated_by_fk references directory.wbt_user (id) on delete set null
);

create unique index if not exists cc_agent_in_skill_group_group_id_agent_id_udx
    on call_center.cc_agent_in_skill_group (skill_group_id, agent_id);

alter table call_center.cc_skill_in_agent
    add column if not exists skill_group_id bigint
        constraint cc_skill_in_agent_skill_group_fk references call_center.cc_skill_group (id) on delete cascade;

create index if not exists cc_skill_in_agent_skill_group_id_index
    on call_center.cc_skill_in_agent (skill_group_id) where skill_group_id is not null;

create or replace view call_center.cc_skill_group_view as
select g.id,
       g.created_at,
       call_center.cc_get_lookup(c.id, coalesce(c.name, c.username::text)::varchar) as created_by,
       g.updated_at,
       call_center.cc_get_lookup(u.id, coalesce(u.name, u.username::text)::varchar) as updated_by,
       g.name,
       g.description,
       g.domain_id,
       coalesce(sk.skills, '[]'::jsonb)                                             as skills,
       coalesce(agents.total_agents, 0)                                            as total_agents,
       coalesce(agents.active_agents, 0)                                           as active_agents
from call_center.cc_skill_group g
         left join directory.wbt_user c on c.id = g.created_by
         left join directory.wbt_user u on u.id = g.updated_by
         left join lateral ( select jsonb_agg(call_center.cc_get_lookup(s.id::bigint, s.name) order by s.name) as skills
                             from call_center.cc_skill_in_group sig
                                      join call_center.cc_skill s on s.id = sig.skill_id
                             where sig.skill_group_id = g.id ) sk on true
         left join lateral ( select count(distinct aig.agent_id)                            as total_agents,
                                    count(distinct sia.agent_id) filter (where sia.enabled) as active_agents
                             from call_center.cc_agent_in_skill_group aig
                                      left join call_center.cc_skill_in_group sig on sig.skill_group_id = g.id
                                      left join call_center.cc_skill_in_agent sia
                                                on sia.agent_id = aig.agent_id and sia.skill_id = sig.skill_id
                             where aig.skill_group_id = g.id ) agents on true;

create or replace function call_center.cc_skill_group_reconcile_agent(p_agent_id integer)
    returns void
    language plpgsql
as
$$
declare
    v_now bigint := (extract(epoch from now()) * 1000)::bigint;
begin

    insert into call_center.cc_skill_in_agent (skill_id, agent_id, capacity, enabled, skill_group_id,
                                               created_at, updated_at)
    select gr.skill_id, p_agent_id, gr.capacity, true, gr.skill_group_id, v_now, v_now
    from (
             select sig.skill_id,
                    max(sig.capacity)::smallint as capacity,
                    min(g.id)                   as skill_group_id
             from call_center.cc_agent a
                      join call_center.cc_agent_in_skill_group aig on aig.agent_id = a.id
                      join call_center.cc_skill_group g on g.id = aig.skill_group_id and g.domain_id = a.domain_id
                      join call_center.cc_skill_in_group sig on sig.skill_group_id = g.id
             where a.id = p_agent_id
             group by sig.skill_id
         ) gr
    where not exists (select 1
                      from call_center.cc_skill_in_agent d
                      where d.agent_id = p_agent_id
                        and d.skill_id = gr.skill_id
                        and d.skill_group_id is null)
    on conflict (agent_id, skill_id) do update
        set capacity       = excluded.capacity,
            skill_group_id = excluded.skill_group_id,
            updated_at     = excluded.updated_at
        where call_center.cc_skill_in_agent.skill_group_id is not null;

    delete
    from call_center.cc_skill_in_agent sia
    where sia.agent_id = p_agent_id
      and sia.skill_group_id is not null
      and not exists (select 1
                      from call_center.cc_agent_in_skill_group aig
                               join call_center.cc_skill_in_group sig on sig.skill_group_id = aig.skill_group_id
                      where aig.agent_id = p_agent_id
                        and sig.skill_id = sia.skill_id);
end;
$$;

create or replace function call_center.cc_skill_group_reconcile_group(p_group_id bigint)
    returns void
    language plpgsql
as
$$
declare
    r record;
begin
    for r in select agent_id from call_center.cc_agent_in_skill_group where skill_group_id = p_group_id
        loop
            perform call_center.cc_skill_group_reconcile_agent(r.agent_id);
        end loop;
end;
$$;
