# Runs the actual backport after being triggered by the backport-trigger.yml workflow.
name: Backport (workflow)
run-name: "backport@${{ github.event.workflow_run.head_branch }} backport for #${{ github.event.workflow_run.run_number }}"

on:
  workflow_run:
    workflows: [ "Backport (trigger)" ]
    types: [ completed ]

permissions: { contents: read }

jobs:
  backport:
    name: Backport
    uses: webitel/reusable-workflows/.github/workflows/_backport.yml@v1.0.6
    permissions:
      id-token: write
      actions: read
      contents: read

    # Only run this job if the triggering workflow was not skipped (and on webitel repositories)
    if: |
      github.event.workflow_run.head_repository.fork == false &&
      github.event.workflow_run.conclusion == 'success'

    with:
      app-id: ${{ vars.DELIVERY_BOT_APP_ID }}

    secrets:
      app-pem: ${{ secrets.DELIVERY_BOT_APP_PEM }}
