name: Dependabot auto-merge
on: pull_request
permissions: {}

jobs:
  dependabot:
    runs-on: [ arc-runner-set ]
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.event.pull_request.head.repo.fork == false
    steps:
      - name: Create Github APP token
        uses: webitel/reusable-workflows/actions/create-github-app-token@create-github-app-token-v1.0.0
        id: app-token
        with:
          app-id: ${{ vars.DELIVERY_BOT_APP_ID }}
          private-key: ${{ secrets.DELIVERY_BOT_APP_PEM }}

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.4.0
        with:
          github-token: ${{ steps.app-token.outputs.token }}

      - name: Approve a PR
        run: gh pr review --approve $PR_URL
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Enable auto-merge for Dependabot PRs
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge --auto --squash $PR_URL
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
