name: Dependabot

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions: {}

jobs:
  merge:
    name: Merge PRs
    runs-on: [ arc-runner-set ]
    if: >
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Create Github APP token
        uses: webitel/reusable-workflows/actions/create-github-app-token@create-github-app-token-v1.0.0
        id: app-token
        with:
          app-id: ${{ vars.DELIVERY_BOT_APP_ID }}
          private-key: ${{ secrets.DELIVERY_BOT_APP_PEM }}

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ steps.app-token.outputs.token }}

      - name: Approve a PR
        run: |
          review_decision=$(gh pr view "$PR_URL" --json reviewDecision -q '.reviewDecision')
          if [ "$review_decision" != "APPROVED" ]; then
            gh pr review --approve "$PR_URL"
          else
            echo "PR already approved ($review_decision), skipping additional approvals to minimize emails/notification noise."
          fi

          # TODO: uncomment when we will have labels sync workflow
          # gh pr edit "$PR_URL" --add-label "auto-merge"

        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Enable auto-merge for Dependabot PRs
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge "$PR_URL" --delete-branch --squash --auto
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
