name: Development

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  prepare:
    name: Prepare
    uses: webitel/reusable-workflows/.github/workflows/go-prepare.yml@fbf131e007e2c7b0bfafcd9bf0f306be596c8836
    with:
      development-branch: master
      triggered-branch: ${{ github.ref_name }}
      build-number: ${{ github.run_number }}
      generated-code-path: ${{ vars.GENERATED_CODE_PATH }}

  checks:
    name: Checks
    needs: [ prepare ]
    uses: webitel/reusable-workflows/.github/workflows/go-checks.yml@fbf131e007e2c7b0bfafcd9bf0f306be596c8836
    permissions:
      security-events: write
      contents: read
      actions: read

    with:
      generated-code: ${{ vars.GENERATED_CODE_PATH != '' }}

  compile:
    name: Build
    needs: [ prepare ]
    uses: webitel/reusable-workflows/.github/workflows/go-build.yml@fbf131e007e2c7b0bfafcd9bf0f306be596c8836
    with:
      version: ${{ needs.prepare.outputs.version }}
      source: ${{ vars.PACKAGE_PATTERN }}
      generated-code: ${{ vars.GENERATED_CODE_PATH != '' }}

  deploy:
    name: Deploy
    needs: [ prepare, compile ]
    uses: webitel/reusable-workflows/.github/workflows/_deploy.yml@fbf131e007e2c7b0bfafcd9bf0f306be596c8836
    secrets: inherit
    with:
      component: ${{ needs.prepare.outputs.component }}
      repository-environment: acceptance