name: PR

on:
  pull_request:

permissions: { contents: read }
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    uses: webitel/reusable-workflows/.github/workflows/go-prepare.yml@cbf5a7837a9320f5054902ba3547a9ce7e47f28e
    with: { only-dependencies: true }

  checks:
    name: Checks
    needs: [ prepare ]
    uses: webitel/reusable-workflows/.github/workflows/go-checks.yml@cbf5a7837a9320f5054902ba3547a9ce7e47f28e
    permissions:
      contents: read
      actions: read
      security-events: write