name: Workflow (webitel-call-center)
run-name: "webitel-call-center@${{ github.ref_name }}#${{ github.run_number }} - ${{ github.event.head_commit.message }}"

on:
  push:
    branches: [ master, "v[0-9]+.[0-9]+" ]

permissions: { contents: read }
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    uses: webitel/reusable-workflows/.github/workflows/golang-prepare.yml@v2
    permissions:
      contents: read
      pull-requests: read
      id-token: write

    with:
      development-branch: ${{ github.event.repository.default_branch }}
      triggered-branch: ${{ github.ref_name }}
      arch: ${{ vars.BUILD_ARCH }}
      codename: ${{ vars.DEB_CODENAME }}

  checks:
    name: Checks
    needs: [ prepare ]
    uses: webitel/reusable-workflows/.github/workflows/golang-checks.yml@v2
    permissions:
      contents: read
      actions: read
      security-events: write

    with:
      changes: ${{ needs.prepare.outputs.changes }}

  compile:
    name: Build
    needs: [ prepare ]
    strategy:
      matrix:
        arch: ${{ fromJSON(needs.prepare.outputs.arch-matrix) }}

    uses: webitel/reusable-workflows/.github/workflows/golang-build.yml@v2
    with:
      arch: ${{ matrix.arch }}
      binary-name: call_center
      ldflags: >
        -s -w
        -X github.com/webitel/call_center/model.BuildNumber=${{ github.run_number }}
        

      version: ${{ needs.prepare.outputs.version }}
      version-build: ${{ github.run_number }}
      prerelease: ${{ github.event.repository.default_branch == github.ref_name && 'dev' || '' }}
      package-name: webitel-call-center
      package-description: ${{ github.event.repository.description }}
      package-contents: |
        src=deploy/systemd/${{ vars.SERVICE_NAME }}.service dst=/etc/systemd/system/${{ vars.SERVICE_NAME }}.service type=config
        

      package-depends: 
      scripts: |
        

  deploy:
    name: Deploy
    if: github.event.repository.private == false
    needs: [ prepare, compile ]
    uses: webitel/reusable-workflows/.github/workflows/_deploy.yml@v2
    secrets: inherit
    with:
      repository-environment: ${{ github.event.repository.default_branch == github.ref_name && 'acceptance' || format('{0}-releases', needs.prepare.outputs.version) }}
      deb-package-pattern: "webitel-call-center*.deb"

  publish:
    name: Publish
    needs: [ prepare, compile, deploy ]
    if: always() && !cancelled() && github.event.repository.private == false && needs.compile.result == 'success' && (needs.deploy.result == 'success' || needs.deploy.result == 'skipped')
    strategy:
      matrix:
        arch: ${{ fromJSON(needs.prepare.outputs.arch-matrix) }}
        codename: ${{ fromJSON(needs.prepare.outputs.codename-matrix) }}

    uses: webitel/reusable-workflows/.github/workflows/_publish-deb.yml@v2
    secrets: inherit
    with:
      arch: ${{ matrix.arch }}
      repository-environment: ${{ github.event.repository.default_branch == github.ref_name && 'acceptance' || format('{0}-releases', needs.prepare.outputs.version) }}
      deb-package-pattern: "webitel-call-center*.deb"
      deb-component: ${{ github.event.repository.default_branch == github.ref_name && 'dev' || format('{0}-releases', needs.prepare.outputs.version) }}
      deb-codename: ${{ matrix.codename }}
      deb-s3-bucket-name: ${{ vars.DEB_S3_BUCKET_NAME }}
      deb-s3-bucket-region: ${{ vars.DEB_S3_DEFAULT_REGION }}
      deb-s3-endpoint: ${{ vars.DEB_S3_ENDPOINT }}
      deb-s3-force-path-style: ${{ vars.DEB_S3_FORCE_PATH_STYLE == 'true' }}

  release:
    name: Release
    needs: [ prepare, publish ]
    if: github.event.repository.default_branch != github.ref_name && needs.publish.result == 'success'
    uses: webitel/reusable-workflows/.github/workflows/_release.yml@v2
    permissions: { contents: write }
    with:
      tag: ${{ format('{0}-{1}', needs.prepare.outputs.version, github.run_number) }}
      tag-target-commitish: ${{ github.sha }}
